import { writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';

const baseDir = 'C:/Users/Kuňákovi/Downloads/Model_Pricer-V2-main_VariantaA_A_to_F_Integrated/.claude/agents';
mkdirSync(baseDir, { recursive: true });

const agents = [
  {name:'mp-spec-security-api-keys',displayName:'API Keys & Secrets Guardian',description:'Secrets management specialist - env vars, API keys, token rotation, Firebase secrets.',color:'#F87171',model:'claude-haiku-4-5-20251001',tools:['Read','Glob','Grep'],permissionMode:'plan',mcpServers:[],domain:'SECURITY',tier:'spec'},
  {name:'mp-spec-security-upload',displayName:'Upload Security Specialist',description:'File upload security - validation, sanitization, size limits, malicious file detection.',color:'#F87171',model:'claude-sonnet-4-5-20250929',tools:['Read','Glob','Grep'],permissionMode:'plan',mcpServers:['context7'],domain:'SECURITY',tier:'spec'},
  {name:'mp-spec-security-auth',displayName:'Auth & Session Security',description:'Authentication flow security - Firebase Auth, session management, token validation.',color:'#F87171',model:'claude-sonnet-4-5-20250929',tools:['Read','Glob','Grep'],permissionMode:'plan',mcpServers:['context7'],domain:'SECURITY',tier:'spec'},
  {name:'mp-spec-security-injection',displayName:'Injection Prevention Specialist',description:'XSS, SQL injection, command injection, postMessage security, OWASP prevention.',color:'#F87171',model:'claude-sonnet-4-5-20250929',tools:['Read','Glob','Grep'],permissionMode:'plan',mcpServers:['context7'],domain:'SECURITY',tier:'spec'},
  {name:'mp-spec-security-gdpr',displayName:'GDPR & Privacy Compliance',description:'Data privacy specialist - GDPR compliance, data retention, consent management, PII handling.',color:'#F87171',model:'claude-sonnet-4-5-20250929',tools:['Read','Glob','Grep'],permissionMode:'plan',mcpServers:[],domain:'SECURITY',tier:'spec'},
  {name:'mp-sr-quality',displayName:'Senior Quality Architect',description:'Quality architecture owner - testing strategy, code review standards, CI/CD gates.',color:'#0891B2',model:'claude-opus-4-6',tools:['Read','Glob','Grep'],permissionMode:'plan',mcpServers:['context7'],domain:'QUALITY',tier:'sr'},
  {name:'mp-mid-quality-code',displayName:'Code Quality Engineer',description:'Code quality guardian - linting, formatting, code smells, maintainability, tech debt.',color:'#06B6D4',model:'claude-opus-4-6',tools:['Read','Glob','Grep'],permissionMode:'plan',mcpServers:['context7'],domain:'QUALITY',tier:'mid'},
  {name:'mp-mid-quality-test',displayName:'Test Quality Engineer',description:'Test strategy owner - coverage analysis, test design, fixture management, mocking patterns.',color:'#06B6D4',model:'claude-opus-4-6',tools:['Read','Glob','Grep','Bash','Write','Edit'],permissionMode:'acceptEdits',mcpServers:['context7'],domain:'QUALITY',tier:'mid'},
  {name:'mp-spec-test-unit',displayName:'Unit Test Specialist',description:'Unit testing expert - Jest/Vitest, component tests, hooks testing, TDD patterns.',color:'#22D3EE',model:'claude-sonnet-4-5-20250929',tools:['Read','Glob','Grep','Bash','Write','Edit'],permissionMode:'acceptEdits',mcpServers:['context7'],domain:'QUALITY',tier:'spec'},
  {name:'mp-spec-test-e2e',displayName:'E2E Test Specialist',description:'End-to-end testing - Playwright, critical user flows, smoke tests, CI integration.',color:'#22D3EE',model:'claude-sonnet-4-5-20250929',tools:['Read','Glob','Grep','Bash','Write','Edit'],permissionMode:'acceptEdits',mcpServers:['context7'],domain:'QUALITY',tier:'spec'},
  {name:'mp-spec-test-api',displayName:'API Test Specialist',description:'API testing expert - contract tests, integration tests, mock servers, API validation.',color:'#22D3EE',model:'claude-sonnet-4-5-20250929',tools:['Read','Glob','Grep','Bash','Write','Edit'],permissionMode:'acceptEdits',mcpServers:['context7'],domain:'QUALITY',tier:'spec'},
  {name:'mp-spec-test-visual',displayName:'Visual Regression Test Specialist',description:'Visual testing - screenshot comparison, Storybook snapshots, CSS regression detection.',color:'#22D3EE',model:'claude-sonnet-4-5-20250929',tools:['Read','Glob','Grep','Bash','Write','Edit'],permissionMode:'acceptEdits',mcpServers:['context7'],domain:'QUALITY',tier:'spec'},
  {name:'mp-spec-test-build',displayName:'Build Test Specialist',description:'Build validation - compile checks, bundle size tests, dependency audits, type checking.',color:'#22D3EE',model:'claude-sonnet-4-5-20250929',tools:['Read','Glob','Grep','Bash','Write','Edit'],permissionMode:'acceptEdits',mcpServers:[],domain:'QUALITY',tier:'spec'},
  {name:'mp-spec-test-browser',displayName:'Browser Compatibility Tester',description:'Cross-browser testing - compatibility checks, polyfill validation, browser-specific bugs.',color:'#22D3EE',model:'claude-haiku-4-5-20251001',tools:['Read','Glob','Grep'],permissionMode:'plan',mcpServers:[],domain:'QUALITY',tier:'spec'},
  {name:'mp-sr-infra',displayName:'Senior Infrastructure Architect',description:'Infrastructure owner - deployment strategy, build pipeline, monitoring, ops automation.',color:'#64748B',model:'claude-opus-4-6',tools:['Read','Glob','Grep'],permissionMode:'plan',mcpServers:['context7'],domain:'INFRA',tier:'sr'},
  {name:'mp-mid-infra-build',displayName:'Build Pipeline Engineer',description:'Build orchestration - Vite config, webpack, bundling, tree-shaking, code splitting.',color:'#94A3B8',model:'claude-opus-4-6',tools:['Read','Glob','Grep','Bash','Write','Edit'],permissionMode:'acceptEdits',mcpServers:['context7'],domain:'INFRA',tier:'mid'},
  {name:'mp-mid-infra-deploy',displayName:'Deployment Engineer',description:'Deployment automation - Firebase Hosting, CI/CD, environment config, rollback strategy.',color:'#94A3B8',model:'claude-opus-4-6',tools:['Read','Glob','Grep','Bash','Write','Edit'],permissionMode:'acceptEdits',mcpServers:['context7'],domain:'INFRA',tier:'mid'},
  {name:'mp-spec-infra-docker',displayName:'Docker & Container Specialist',description:'Container orchestration - Dockerfiles, multi-stage builds, image optimization, compose.',color:'#CBD5E1',model:'claude-sonnet-4-5-20250929',tools:['Read','Glob','Grep','Bash','Write','Edit'],permissionMode:'acceptEdits',mcpServers:['context7'],domain:'INFRA
