/**
 * Quick Theme presets for Widget Builder V3.
 * Each preset is a complete theme object (all 56 properties).
 * Based on Design Report V3 section 3.2.
 */
import { getDefaultWidgetTheme } from '@/utils/widgetThemeStorage';

const defaults = getDefaultWidgetTheme();

export const QUICK_THEMES = [
  {
    id: 'modern-dark',
    name: { cs: 'Modern Dark', en: 'Modern Dark' },
    colors: ['#1A1A2E', '#3B82F6', '#EAEAEA'],
    theme: {
      ...defaults,
      backgroundColor: '#1A1A2E',
      cardColor: '#16213E',
      headerColor: '#EAEAEA',
      textColor: '#D1D5DB',
      mutedColor: '#9CA3AF',
      buttonPrimaryColor: '#3B82F6',
      buttonTextColor: '#FFFFFF',
      buttonHoverColor: '#2563EB',
      inputBgColor: '#16213E',
      inputBorderColor: '#2E3340',
      inputFocusColor: '#3B82F6',
      summaryBgColor: '#16213E',
      borderColor: '#2E3340',
      headerBgColor: '#1A1A2E',
      uploadBgColor: '#16213E',
      uploadBorderColor: '#2E3340',
      uploadBorderHoverColor: '#3B82F6',
      uploadIconColor: '#6B7280',
      stepperActiveColor: '#3B82F6',
      stepperCompletedColor: '#10B981',
      stepperInactiveColor: '#374151',
      configBgColor: '#16213E',
      configLabelColor: '#D1D5DB',
      feesBgColor: '#16213E',
      feesCheckboxColor: '#3B82F6',
      summaryHeaderColor: '#EAEAEA',
      summaryDividerColor: '#2E3340',
      summaryTotalBgColor: '#1E3A5F',
      footerBgColor: 'transparent',
      footerTextColor: '#6B7280',
      footerLinkColor: '#3B82F6',
      skeletonBaseColor: '#2E3340',
      skeletonShineColor: '#374151',
      cardShadow: 'medium',
    },
  },
  {
    id: 'clean-light',
    name: { cs: 'Clean Light', en: 'Clean Light' },
    colors: ['#FAFBFC', '#059669', '#1F2937'],
    theme: {
      ...defaults,
      backgroundColor: '#FAFBFC',
      cardColor: '#FFFFFF',
      headerColor: '#1F2937',
      textColor: '#374151',
      mutedColor: '#6B7280',
      buttonPrimaryColor: '#059669',
      buttonTextColor: '#FFFFFF',
      buttonHoverColor: '#047857',
      inputBgColor: '#FFFFFF',
      inputBorderColor: '#D1D5DB',
      inputFocusColor: '#059669',
      summaryBgColor: '#F0FDF4',
      borderColor: '#E5E7EB',
      headerBgColor: '#FFFFFF',
      uploadBgColor: '#F0FDF4',
      uploadBorderColor: '#D1FAE5',
      uploadBorderHoverColor: '#059669',
      uploadIconColor: '#6EE7B7',
      stepperActiveColor: '#059669',
      stepperCompletedColor: '#059669',
      stepperInactiveColor: '#E5E7EB',
      configBgColor: '#FFFFFF',
      configLabelColor: '#374151',
      feesBgColor: '#F0FDF4',
      feesCheckboxColor: '#059669',
      summaryHeaderColor: '#1F2937',
      summaryDividerColor: '#E5E7EB',
      summaryTotalBgColor: '#ECFDF5',
      footerBgColor: 'transparent',
      footerTextColor: '#9CA3AF',
      footerLinkColor: '#059669',
      skeletonBaseColor: '#E5E7EB',
      skeletonShineColor: '#F3F4F6',
      cardShadow: 'subtle',
    },
  },
  {
    id: 'professional-blue',
    name: { cs: 'Professional Blue', en: 'Professional Blue' },
    colors: ['#F0F4F8', '#1E40AF', '#1E293B'],
    theme: {
      ...defaults,
      backgroundColor: '#F0F4F8',
      cardColor: '#FFFFFF',
      headerColor: '#1E293B',
      textColor: '#334155',
      mutedColor: '#64748B',
      buttonPrimaryColor: '#1E40AF',
      buttonTextColor: '#FFFFFF',
      buttonHoverColor: '#1E3A8A',
      inputBgColor: '#FFFFFF',
      inputBorderColor: '#CBD5E1',
      inputFocusColor: '#1E40AF',
      summaryBgColor: '#EFF6FF',
      borderColor: '#E2E8F0',
      headerBgColor: '#FFFFFF',
      uploadBgColor: '#EFF6FF',
      uploadBorderColor: '#BFDBFE',
      uploadBorderHoverColor: '#1E40AF',
      uploadIconColor: '#93C5FD',
      stepperActiveColor: '#1E40AF',
      stepperCompletedColor: '#059669',
      stepperInactiveColor: '#E2E8F0',
      configBgColor: '#FFFFFF',
      configLabelColor: '#334155',
      feesBgColor: '#F8FAFC',
      feesCheckboxColor: '#1E40AF',
      summaryHeaderColor: '#1E293B',
      summaryDividerColor: '#E2E8F0',
      summaryTotalBgColor: '#DBEAFE',
      footerBgColor: 'transparent',
      footerTextColor: '#94A3B8',
      footerLinkColor: '#1E40AF',
      skeletonBaseColor: '#E2E8F0',
      skeletonShineColor: '#F1F5F9',
      cardShadow: 'subtle',
    },
  },
  {
    id: 'warm-neutral',
    name: { cs: 'Warm Neutral', en: 'Warm Neutral' },
    colors: ['#F5F0EB', '#D97706', '#292524'],
    theme: {
      ...defaults,
      backgroundColor: '#F5F0EB',
      cardColor: '#FEFDFB',
      headerColor: '#292524',
      textColor: '#44403C',
      mutedColor: '#78716C',
      buttonPrimaryColor: '#D97706',
      buttonTextColor: '#FFFFFF',
      buttonHoverColor: '#B45309',
      inputBgColor: '#FEFDFB',
      inputBorderColor: '#D6D3D1',
      inputFocusColor: '#D97706',
      summaryBgColor: '#FFFBEB',
      borderColor: '#E7E5E4',
      headerBgColor: '#FEFDFB',
      uploadBgColor: '#FFFBEB',
      uploadBorderColor: '#FDE68A',
      uploadBorderHoverColor: '#D97706',
      uploadIconColor: '#FCD34D',
      stepperActiveColor: '#D97706',
      stepperCompletedColor: '#059669',
      stepperInactiveColor: '#E7E5E4',
      configBgColor: '#FEFDFB',
      configLabelColor: '#44403C',
      feesBgColor: '#FFFBEB',
      feesCheckboxColor: '#D97706',
      summaryHeaderColor: '#292524',
      summaryDividerColor: '#E7E5E4',
      summaryTotalBgColor: '#FEF3C7',
      footerBgColor: 'transparent',
      footerTextColor: '#A8A29E',
      footerLinkColor: '#D97706',
      skeletonBaseColor: '#E7E5E4',
      skeletonShineColor: '#F5F5F4',
      cardShadow: 'subtle',
    },
  },
];

/**
 * Find a quick theme by ID.
 * @param {string} id Theme ID
 * @returns {object|null}
 */
export function getQuickTheme(id) {
  return QUICK_THEMES.find((t) => t.id === id) || null;
}

/**
 * "Custom" is not a preset — it means the user's current manual edits.
 * Use this constant for the dropdown when no preset matches.
 */
export const CUSTOM_THEME_ID = 'custom';
