/**
 * calculatorBlocks.js -- Calculator-specific block definitions for the Widget Builder.
 *
 * These blocks map directly to functional sections of the 3D print calculator widget.
 * LOCKED blocks (upload-zone, model-viewer, print-config, price-breakdown,
 * checkout-form, order-confirmation) cannot be deleted because they are required
 * for the calculator to function, but they CAN be restyled and repositioned.
 *
 * Non-locked calculator blocks (coupon-input, express-tier, shipping-selector,
 * upsell-panel, promo-bar, shopify-cart-button) can be added/removed freely.
 *
 * Steps: 1=Upload, 2=Config, 3=Pricing, 4=Order, 5=Confirmation
 */

// ---------------------------------------------------------------------------
// Shared editable property presets (DRY helpers)
// ---------------------------------------------------------------------------

/** Standard background + border properties reused across most blocks. */
const COMMON_CONTAINER_PROPS = [
  {
    key: 'backgroundColor',
    label: 'Background',
    labelCs: 'Pozadi',
    type: 'color',
    default: '#ffffff',
    group: 'container',
  },
  {
    key: 'borderColor',
    label: 'Border Color',
    labelCs: 'Barva ramecku',
    type: 'color',
    default: '#e5e7eb',
    group: 'container',
  },
  {
    key: 'borderWidth',
    label: 'Border Width',
    labelCs: 'Sirka ramecku',
    type: 'number',
    default: 1,
    min: 0,
    max: 8,
    unit: 'px',
    group: 'container',
  },
  {
    key: 'borderStyle',
    label: 'Border Style',
    labelCs: 'Styl ramecku',
    type: 'select',
    default: 'solid',
    options: [
      { value: 'none', label: 'None', labelCs: 'Zadny' },
      { value: 'solid', label: 'Solid', labelCs: 'Plny' },
      { value: 'dashed', label: 'Dashed', labelCs: 'Carkovany' },
      { value: 'dotted', label: 'Dotted', labelCs: 'Teckovany' },
    ],
    group: 'container',
  },
  {
    key: 'borderRadius',
    label: 'Corner Radius',
    labelCs: 'Zaobleni rohu',
    type: 'number',
    default: 8,
    min: 0,
    max: 32,
    unit: 'px',
    group: 'container',
  },
  {
    key: 'padding',
    label: 'Padding',
    labelCs: 'Vnitrni odsazeni',
    type: 'spacing',
    default: { top: 24, right: 24, bottom: 24, left: 24 },
    group: 'container',
  },
  {
    key: 'margin',
    label: 'Margin',
    labelCs: 'Vnejsi odsazeni',
    type: 'spacing',
    default: { top: 0, right: 0, bottom: 16, left: 0 },
    group: 'container',
  },
  {
    key: 'boxShadow',
    label: 'Shadow',
    labelCs: 'Stin',
    type: 'shadow',
    default: 'none',
    options: [
      { value: 'none', label: 'None', labelCs: 'Zadny' },
      { value: '0 1px 3px rgba(0,0,0,0.1)', label: 'Small', labelCs: 'Maly' },
      { value: '0 4px 12px rgba(0,0,0,0.1)', label: 'Medium', labelCs: 'Stredni' },
      { value: '0 8px 24px rgba(0,0,0,0.12)', label: 'Large', labelCs: 'Velky' },
    ],
    group: 'container',
  },
  {
    key: 'opacity',
    label: 'Opacity',
    labelCs: 'Pruhlednost',
    type: 'number',
    default: 1,
    min: 0,
    max: 1,
    step: 0.05,
    group: 'container',
  },
];

/** Typography properties shared by blocks that display titles/descriptions. */
const COMMON_TITLE_PROPS = [
  {
    key: 'titleFontFamily',
    label: 'Title Font',
    labelCs: 'Font nadpisu',
    type: 'font',
    default: 'inherit',
    group: 'typography',
  },
  {
    key: 'titleFontSize',
    label: 'Title Size',
    labelCs: 'Velikost nadpisu',
    type: 'number',
    default: 18,
    min: 12,
    max: 48,
    unit: 'px',
    group: 'typography',
  },
  {
    key: 'titleFontWeight',
    label: 'Title Weight',
    labelCs: 'Tucnost nadpisu',
    type: 'select',
    default: '600',
    options: [
      { value: '300', label: 'Light', labelCs: 'Tenky' },
      { value: '400', label: 'Normal', labelCs: 'Normalni' },
      { value: '500', label: 'Medium', labelCs: 'Stredni' },
      { value: '600', label: 'Semi-bold', labelCs: 'Polotucny' },
      { value: '700', label: 'Bold', labelCs: 'Tucny' },
    ],
    group: 'typography',
  },
  {
    key: 'titleColor',
    label: 'Title Color',
    labelCs: 'Barva nadpisu',
    type: 'color',
    default: '#111827',
    group: 'typography',
  },
  {
    key: 'titleAlignment',
    label: 'Title Alignment',
    labelCs: 'Zarovnani nadpisu',
    type: 'select',
    default: 'left',
    options: [
      { value: 'left', label: 'Left', labelCs: 'Vlevo' },
      { value: 'center', label: 'Center', labelCs: 'Na stred' },
      { value: 'right', label: 'Right', labelCs: 'Vpravo' },
    ],
    group: 'typography',
  },
];

/** Description/subtitle typography. */
const COMMON_DESCRIPTION_PROPS = [
  {
    key: 'descriptionFontSize',
    label: 'Description Size',
    labelCs: 'Velikost popisku',
    type: 'number',
    default: 14,
    min: 10,
    max: 24,
    unit: 'px',
    group: 'typography',
  },
  {
    key: 'descriptionColor',
    label: 'Description Color',
    labelCs: 'Barva popisku',
    type: 'color',
    default: '#6b7280',
    group: 'typography',
  },
];

// ---------------------------------------------------------------------------
// Calculator blocks
// ---------------------------------------------------------------------------

export const calculatorBlocks = [
  // -------------------------------------------------------------------------
  // STEP 1 — Upload
  // -------------------------------------------------------------------------
  {
    id: 'upload-zone',
    name: 'Upload Zone',
    nameCs: 'Zona nahrani',
    category: 'calculator',
    step: 1,
    icon: 'Upload',
    locked: true,
    canReposition: true,
    canRestyle: true,
    description: 'Primary file upload area for 3D models (STL, 3MF, OBJ).',
    descriptionCs: 'Hlavni oblast pro nahrani 3D modelu (STL, 3MF, OBJ).',
    defaultProps: {
      backgroundColor: '#ffffff',
      borderColor: '#d1d5db',
      borderWidth: 2,
      borderStyle: 'dashed',
      borderRadius: 12,
      padding: { top: 32, right: 32, bottom: 32, left: 32 },
      margin: { top: 0, right: 0, bottom: 16, left: 0 },
      boxShadow: 'none',
      opacity: 1,
      title: 'Upload your 3D model',
      titleCs: 'Nahrajte svuj 3D model',
      description: 'Drag & drop or click to browse. Supported formats: STL, 3MF, OBJ.',
      descriptionCs: 'Pretahnete sem nebo kliknete. Podporovane formaty: STL, 3MF, OBJ.',
      iconColor: '#9ca3af',
      iconSize: 48,
      hoverBorderColor: '#3b82f6',
      hoverBackgroundColor: '#eff6ff',
      maxFileSize: '100MB',
      showFileTypes: true,
      titleFontFamily: 'inherit',
      titleFontSize: 18,
      titleFontWeight: '600',
      titleColor: '#111827',
      titleAlignment: 'center',
      descriptionFontSize: 14,
      descriptionColor: '#6b7280',
    },
    editableProperties: [
      ...COMMON_CONTAINER_PROPS.map((p) => ({
        ...p,
        default: p.key === 'borderStyle' ? 'dashed' :
          p.key === 'borderWidth' ? 2 :
            p.key === 'borderColor' ? '#d1d5db' :
              p.key === 'borderRadius' ? 12 :
                p.key === 'padding' ? { top: 32, right: 32, bottom: 32, left: 32 } :
                  p.default,
      })),
      {
        key: 'title',
        label: 'Title Text',
        labelCs: 'Text nadpisu',
        type: 'text',
        default: 'Upload your 3D model',
        group: 'content',
      },
      {
        key: 'description',
        label: 'Description',
        labelCs: 'Popisek',
        type: 'text',
        default: 'Drag & drop or click to browse',
        group: 'content',
      },
      ...COMMON_TITLE_PROPS.map((p) => ({
        ...p,
        default: p.key === 'titleAlignment' ? 'center' : p.default,
      })),
      ...COMMON_DESCRIPTION_PROPS,
      {
        key: 'iconColor',
        label: 'Icon Color',
        labelCs: 'Barva ikony',
        type: 'color',
        default: '#9ca3af',
        group: 'icon',
      },
      {
        key: 'iconSize',
        label: 'Icon Size',
        labelCs: 'Velikost ikony',
        type: 'number',
        default: 48,
        min: 24,
        max: 96,
        unit: 'px',
        group: 'icon',
      },
      {
        key: 'hoverBorderColor',
        label: 'Hover Border',
        labelCs: 'Ramecek pri navrhu',
        type: 'color',
        default: '#3b82f6',
        group: 'interaction',
      },
      {
        key: 'hoverBackgroundColor',
        label: 'Hover Background',
        labelCs: 'Pozadi pri navrhu',
        type: 'color',
        default: '#eff6ff',
        group: 'interaction',
      },
      {
        key: 'showFileTypes',
        label: 'Show File Types',
        labelCs: 'Zobrazit typy souboru',
        type: 'boolean',
        default: true,
        group: 'content',
      },
    ],
  },

  // -------------------------------------------------------------------------
  // STEP 2 — Configuration
  // -------------------------------------------------------------------------
  {
    id: 'model-viewer',
    name: '3D Model Viewer',
    nameCs: '3D nahled modelu',
    category: 'calculator',
    step: 2,
    icon: 'Box',
    locked: true,
    canReposition: true,
    canRestyle: true,
    description: 'Interactive 3D preview of the uploaded model.',
    descriptionCs: 'Interaktivni 3D nahled nahraneho modelu.',
    defaultProps: {
      backgroundColor: '#f9fafb',
      borderColor: '#e5e7eb',
      borderWidth: 1,
      borderStyle: 'solid',
      borderRadius: 8,
      padding: { top: 0, right: 0, bottom: 0, left: 0 },
      margin: { top: 0, right: 0, bottom: 16, left: 0 },
      boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
      opacity: 1,
      minHeight: 300,
      maxHeight: 500,
      showControls: true,
      showDimensions: true,
      autoRotate: false,
      wireframeToggle: true,
      controlsColor: '#6b7280',
      controlsSize: 14,
    },
    editableProperties: [
      ...COMMON_CONTAINER_PROPS.map((p) => ({
        ...p,
        default: p.key === 'backgroundColor' ? '#f9fafb' :
          p.key === 'padding' ? { top: 0, right: 0, bottom: 0, left: 0 } :
            p.key === 'boxShadow' ? '0 1px 3px rgba(0,0,0,0.1)' :
              p.default,
      })),
      {
        key: 'minHeight',
        label: 'Min Height',
        labelCs: 'Minimalni vyska',
        type: 'number',
        default: 300,
        min: 150,
        max: 800,
        unit: 'px',
        group: 'dimensions',
      },
      {
        key: 'maxHeight',
        label: 'Max Height',
        labelCs: 'Maximalni vyska',
        type: 'number',
        default: 500,
        min: 200,
        max: 1000,
        unit: 'px',
        group: 'dimensions',
      },
      {
        key: 'showControls',
        label: 'Show Controls',
        labelCs: 'Zobrazit ovladani',
        type: 'boolean',
        default: true,
        group: 'viewer',
      },
      {
        key: 'showDimensions',
        label: 'Show Dimensions',
        labelCs: 'Zobrazit rozmery',
        type: 'boolean',
        default: true,
        group: 'viewer',
      },
      {
        key: 'autoRotate',
        label: 'Auto-Rotate',
        labelCs: 'Automaticka rotace',
        type: 'boolean',
        default: false,
        group: 'viewer',
      },
      {
        key: 'wireframeToggle',
        label: 'Wireframe Toggle',
        labelCs: 'Prepinac wireframe',
        type: 'boolean',
        default: true,
        group: 'viewer',
      },
      {
        key: 'controlsColor',
        label: 'Controls Color',
        labelCs: 'Barva ovladani',
        type: 'color',
        default: '#6b7280',
        group: 'viewer',
      },
      {
        key: 'controlsSize',
        label: 'Controls Size',
        labelCs: 'Velikost ovladani',
        type: 'number',
        default: 14,
        min: 10,
        max: 24,
        unit: 'px',
        group: 'viewer',
      },
    ],
  },

  {
    id: 'print-config',
    name: 'Print Configuration',
    nameCs: 'Konfigurace tisku',
    category: 'calculator',
    step: 2,
    icon: 'Settings',
    locked: true,
    canReposition: true,
    canRestyle: true,
    description: 'Material, quality, infill, and quantity selectors.',
    descriptionCs: 'Vyber materialu, kvality, vyplne a mnozstvi.',
    defaultProps: {
      backgroundColor: '#ffffff',
      borderColor: '#e5e7eb',
      borderWidth: 1,
      borderStyle: 'solid',
      borderRadius: 8,
      padding: { top: 20, right: 20, bottom: 20, left: 20 },
      margin: { top: 0, right: 0, bottom: 16, left: 0 },
      boxShadow: 'none',
      opacity: 1,
      labelColor: '#374151',
      labelFontSize: 14,
      labelFontWeight: '500',
      inputBorderColor: '#d1d5db',
      inputBorderRadius: 6,
      inputBackgroundColor: '#ffffff',
      inputFocusBorderColor: '#3b82f6',
      sectionGap: 16,
      showLabels: true,
      showHelperText: true,
      helperTextColor: '#9ca3af',
      helperTextFontSize: 12,
      titleFontFamily: 'inherit',
      titleFontSize: 16,
      titleFontWeight: '600',
      titleColor: '#111827',
      titleAlignment: 'left',
    },
    editableProperties: [
      ...COMMON_CONTAINER_PROPS,
      ...COMMON_TITLE_PROPS.map((p) => ({
        ...p,
        default: p.key === 'titleFontSize' ? 16 : p.default,
      })),
      {
        key: 'labelColor',
        label: 'Label Color',
        labelCs: 'Barva popisku',
        type: 'color',
        default: '#374151',
        group: 'form',
      },
      {
        key: 'labelFontSize',
        label: 'Label Size',
        labelCs: 'Velikost popisku',
        type: 'number',
        default: 14,
        min: 10,
        max: 20,
        unit: 'px',
        group: 'form',
      },
      {
        key: 'labelFontWeight',
        label: 'Label Weight',
        labelCs: 'Tucnost popisku',
        type: 'select',
        default: '500',
        options: [
          { value: '400', label: 'Normal', labelCs: 'Normalni' },
          { value: '500', label: 'Medium', labelCs: 'Stredni' },
          { value: '600', label: 'Semi-bold', labelCs: 'Polotucny' },
        ],
        group: 'form',
      },
      {
        key: 'inputBorderColor',
        label: 'Input Border',
        labelCs: 'Ramecek inputu',
        type: 'color',
        default: '#d1d5db',
        group: 'form',
      },
      {
        key: 'inputBorderRadius',
        label: 'Input Radius',
        labelCs: 'Zaobleni inputu',
        type: 'number',
        default: 6,
        min: 0,
        max: 16,
        unit: 'px',
        group: 'form',
      },
      {
        key: 'inputBackgroundColor',
        label: 'Input Background',
        labelCs: 'Pozadi inputu',
        type: 'color',
        default: '#ffffff',
        group: 'form',
      },
      {
        key: 'inputFocusBorderColor',
        label: 'Input Focus Border',
        labelCs: 'Ramecek pri fokusu',
        type: 'color',
        default: '#3b82f6',
        group: 'form',
      },
      {
        key: 'sectionGap',
        label: 'Section Gap',
        labelCs: 'Mezera mezi sekcemi',
        type: 'number',
        default: 16,
        min: 4,
        max: 48,
        unit: 'px',
        group: 'layout',
      },
      {
        key: 'showLabels',
        label: 'Show Labels',
        labelCs: 'Zobrazit popisky',
        type: 'boolean',
        default: true,
        group: 'content',
      },
      {
        key: 'showHelperText',
        label: 'Show Helper Text',
        labelCs: 'Zobrazit napovedu',
        type: 'boolean',
        default: true,
        group: 'content',
      },
      {
        key: 'helperTextColor',
        label: 'Helper Text Color',
        labelCs: 'Barva napovedy',
        type: 'color',
        default: '#9ca3af',
        group: 'form',
      },
      {
        key: 'helperTextFontSize',
        label: 'Helper Text Size',
        labelCs: 'Velikost napovedy',
        type: 'number',
        default: 12,
        min: 10,
        max: 16,
        unit: 'px',
        group: 'form',
      },
    ],
  },

  // -------------------------------------------------------------------------
  // STEP 3 — Pricing
  // -------------------------------------------------------------------------
  {
    id: 'price-breakdown',
    name: 'Price Breakdown',
    nameCs: 'Rozpis ceny',
    category: 'calculator',
    step: 3,
    icon: 'Receipt',
    locked: true,
    canReposition: true,
    canRestyle: true,
    description: 'Detailed price summary table with line items and total.',
    descriptionCs: 'Detailni tabulka ceny s polozkami a celkovou cenou.',
    defaultProps: {
      backgroundColor: '#ffffff',
      borderColor: '#e5e7eb',
      borderWidth: 1,
      borderStyle: 'solid',
      borderRadius: 8,
      padding: { top: 20, right: 20, bottom: 20, left: 20 },
      margin: { top: 0, right: 0, bottom: 16, left: 0 },
      boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
      opacity: 1,
      headerColor: '#111827',
      headerFontSize: 16,
      headerFontWeight: '600',
      lineItemColor: '#374151',
      lineItemFontSize: 14,
      lineValueColor: '#111827',
      lineValueFontWeight: '500',
      dividerColor: '#e5e7eb',
      dividerThickness: 1,
      totalBackgroundColor: '#f0fdf4',
      totalColor: '#059669',
      totalFontSize: 20,
      totalFontWeight: '700',
      totalBorderRadius: 6,
      totalPadding: { top: 12, right: 16, bottom: 12, left: 16 },
      showCurrencySymbol: true,
      currencyPosition: 'after',
      rowGap: 8,
      titleFontFamily: 'inherit',
      titleFontSize: 16,
      titleFontWeight: '600',
      titleColor: '#111827',
      titleAlignment: 'left',
    },
    editableProperties: [
      ...COMMON_CONTAINER_PROPS,
      ...COMMON_TITLE_PROPS.map((p) => ({
        ...p,
        default: p.key === 'titleFontSize' ? 16 : p.default,
      })),
      {
        key: 'headerColor',
        label: 'Header Color',
        labelCs: 'Barva hlavicky',
        type: 'color',
        default: '#111827',
        group: 'pricing',
      },
      {
        key: 'headerFontSize',
        label: 'Header Size',
        labelCs: 'Velikost hlavicky',
        type: 'number',
        default: 16,
        min: 12,
        max: 28,
        unit: 'px',
        group: 'pricing',
      },
      {
        key: 'lineItemColor',
        label: 'Line Item Color',
        labelCs: 'Barva polozky',
        type: 'color',
        default: '#374151',
        group: 'pricing',
      },
      {
        key: 'lineItemFontSize',
        label: 'Line Item Size',
        labelCs: 'Velikost polozky',
        type: 'number',
        default: 14,
        min: 10,
        max: 20,
        unit: 'px',
        group: 'pricing',
      },
      {
        key: 'lineValueColor',
        label: 'Value Color',
        labelCs: 'Barva castky',
        type: 'color',
        default: '#111827',
        group: 'pricing',
      },
      {
        key: 'dividerColor',
        label: 'Divider Color',
        labelCs: 'Barva oddelovace',
        type: 'color',
        default: '#e5e7eb',
        group: 'pricing',
      },
      {
        key: 'dividerThickness',
        label: 'Divider Thickness',
        labelCs: 'Tloustka oddelovace',
        type: 'number',
        default: 1,
        min: 0,
        max: 4,
        unit: 'px',
        group: 'pricing',
      },
      {
        key: 'totalBackgroundColor',
        label: 'Total Background',
        labelCs: 'Pozadi celkove ceny',
        type: 'color',
        default: '#f0fdf4',
        group: 'pricing',
      },
      {
        key: 'totalColor',
        label: 'Total Color',
        labelCs: 'Barva celkove ceny',
        type: 'color',
        default: '#059669',
        group: 'pricing',
      },
      {
        key: 'totalFontSize',
        label: 'Total Size',
        labelCs: 'Velikost celkove ceny',
        type: 'number',
        default: 20,
        min: 14,
        max: 36,
        unit: 'px',
        group: 'pricing',
      },
      {
        key: 'totalFontWeight',
        label: 'Total Weight',
        labelCs: 'Tucnost celkove ceny',
        type: 'select',
        default: '700',
        options: [
          { value: '500', label: 'Medium', labelCs: 'Stredni' },
          { value: '600', label: 'Semi-bold', labelCs: 'Polotucny' },
          { value: '700', label: 'Bold', labelCs: 'Tucny' },
          { value: '800', label: 'Extra-bold', labelCs: 'Extra tucny' },
        ],
        group: 'pricing',
      },
      {
        key: 'totalBorderRadius',
        label: 'Total Radius',
        labelCs: 'Zaobleni celkove ceny',
        type: 'number',
        default: 6,
        min: 0,
        max: 16,
        unit: 'px',
        group: 'pricing',
      },
      {
        key: 'showCurrencySymbol',
        label: 'Show Currency',
        labelCs: 'Zobrazit menu',
        type: 'boolean',
        default: true,
        group: 'content',
      },
      {
        key: 'currencyPosition',
        label: 'Currency Position',
        labelCs: 'Pozice meny',
        type: 'select',
        default: 'after',
        options: [
          { value: 'before', label: 'Before', labelCs: 'Pred' },
          { value: 'after', label: 'After', labelCs: 'Za' },
        ],
        group: 'content',
      },
      {
        key: 'rowGap',
        label: 'Row Gap',
        labelCs: 'Mezera mezi radky',
        type: 'number',
        default: 8,
        min: 0,
        max: 24,
        unit: 'px',
        group: 'layout',
      },
    ],
  },

  // -------------------------------------------------------------------------
  // STEP 4 — Order / Checkout
  // -------------------------------------------------------------------------
  {
    id: 'checkout-form',
    name: 'Checkout Form',
    nameCs: 'Objednavkovy formular',
    category: 'calculator',
    step: 4,
    icon: 'ClipboardList',
    locked: true,
    canReposition: true,
    canRestyle: true,
    description: 'Customer details form for order submission.',
    descriptionCs: 'Formular pro zadani udaju zakaznika a odeslani objednavky.',
    defaultProps: {
      backgroundColor: '#ffffff',
      borderColor: '#e5e7eb',
      borderWidth: 1,
      borderStyle: 'solid',
      borderRadius: 8,
      padding: { top: 24, right: 24, bottom: 24, left: 24 },
      margin: { top: 0, right: 0, bottom: 16, left: 0 },
      boxShadow: 'none',
      opacity: 1,
      labelColor: '#374151',
      labelFontSize: 14,
      labelFontWeight: '500',
      inputBorderColor: '#d1d5db',
      inputBorderRadius: 6,
      inputBackgroundColor: '#ffffff',
      inputFocusBorderColor: '#3b82f6',
      inputPadding: { top: 10, right: 12, bottom: 10, left: 12 },
      inputFontSize: 14,
      placeholderColor: '#9ca3af',
      errorColor: '#ef4444',
      errorFontSize: 12,
      sectionGap: 16,
      fieldGap: 12,
      submitButtonColor: '#3b82f6',
      submitButtonTextColor: '#ffffff',
      submitButtonHoverColor: '#2563eb',
      submitButtonRadius: 8,
      submitButtonFontSize: 16,
      submitButtonFontWeight: '600',
      submitButtonPadding: { top: 12, right: 24, bottom: 12, left: 24 },
      submitButtonText: 'Place Order',
      submitButtonTextCs: 'Odeslat objednavku',
      titleFontFamily: 'inherit',
      titleFontSize: 18,
      titleFontWeight: '600',
      titleColor: '#111827',
      titleAlignment: 'left',
    },
    editableProperties: [
      ...COMMON_CONTAINER_PROPS,
      ...COMMON_TITLE_PROPS,
      {
        key: 'labelColor',
        label: 'Label Color',
        labelCs: 'Barva popisku',
        type: 'color',
        default: '#374151',
        group: 'form',
      },
      {
        key: 'labelFontSize',
        label: 'Label Size',
        labelCs: 'Velikost popisku',
        type: 'number',
        default: 14,
        min: 10,
        max: 20,
        unit: 'px',
        group: 'form',
      },
      {
        key: 'inputBorderColor',
        label: 'Input Border',
        labelCs: 'Ramecek inputu',
        type: 'color',
        default: '#d1d5db',
        group: 'form',
      },
      {
        key: 'inputBorderRadius',
        label: 'Input Radius',
        labelCs: 'Zaobleni inputu',
        type: 'number',
        default: 6,
        min: 0,
        max: 16,
        unit: 'px',
        group: 'form',
      },
      {
        key: 'inputBackgroundColor',
        label: 'Input Background',
        labelCs: 'Pozadi inputu',
        type: 'color',
        default: '#ffffff',
        group: 'form',
      },
      {
        key: 'inputFocusBorderColor',
        label: 'Input Focus Border',
        labelCs: 'Ramecek pri fokusu',
        type: 'color',
        default: '#3b82f6',
        group: 'form',
      },
      {
        key: 'inputFontSize',
        label: 'Input Font Size',
        labelCs: 'Velikost textu inputu',
        type: 'number',
        default: 14,
        min: 12,
        max: 20,
        unit: 'px',
        group: 'form',
      },
      {
        key: 'placeholderColor',
        label: 'Placeholder Color',
        labelCs: 'Barva zastupneho textu',
        type: 'color',
        default: '#9ca3af',
        group: 'form',
      },
      {
        key: 'errorColor',
        label: 'Error Color',
        labelCs: 'Barva chyby',
        type: 'color',
        default: '#ef4444',
        group: 'form',
      },
      {
        key: 'sectionGap',
        label: 'Section Gap',
        labelCs: 'Mezera mezi sekcemi',
        type: 'number',
        default: 16,
        min: 4,
        max: 48,
        unit: 'px',
        group: 'layout',
      },
      {
        key: 'fieldGap',
        label: 'Field Gap',
        labelCs: 'Mezera mezi poli',
        type: 'number',
        default: 12,
        min: 4,
        max: 32,
        unit: 'px',
        group: 'layout',
      },
      {
        key: 'submitButtonColor',
        label: 'Submit Button Color',
        labelCs: 'Barva tlacitka odeslani',
        type: 'color',
        default: '#3b82f6',
        group: 'button',
      },
      {
        key: 'submitButtonTextColor',
        label: 'Submit Text Color',
        labelCs: 'Barva textu tlacitka',
        type: 'color',
        default: '#ffffff',
        group: 'button',
      },
      {
        key: 'submitButtonHoverColor',
        label: 'Submit Hover Color',
        labelCs: 'Barva pri navrhu',
        type: 'color',
        default: '#2563eb',
        group: 'button',
      },
      {
        key: 'submitButtonRadius',
        label: 'Submit Radius',
        labelCs: 'Zaobleni tlacitka',
        type: 'number',
        default: 8,
        min: 0,
        max: 24,
        unit: 'px',
        group: 'button',
      },
      {
        key: 'submitButtonFontSize',
        label: 'Submit Font Size',
        labelCs: 'Velikost fontu tlacitka',
        type: 'number',
        default: 16,
        min: 12,
        max: 24,
        unit: 'px',
        group: 'button',
      },
      {
        key: 'submitButtonText',
        label: 'Submit Text',
        labelCs: 'Text tlacitka',
        type: 'text',
        default: 'Place Order',
        group: 'content',
      },
    ],
  },

  // -------------------------------------------------------------------------
  // STEP 5 — Confirmation
  // -------------------------------------------------------------------------
  {
    id: 'order-confirmation',
    name: 'Order Confirmation',
    nameCs: 'Potvrzeni objednavky',
    category: 'calculator',
    step: 5,
    icon: 'CheckCircle',
    locked: true,
    canReposition: true,
    canRestyle: true,
    description: 'Success display after order placement.',
    descriptionCs: 'Zobrazeni uspesneho odeslani objednavky.',
    defaultProps: {
      backgroundColor: '#f0fdf4',
      borderColor: '#bbf7d0',
      borderWidth: 1,
      borderStyle: 'solid',
      borderRadius: 12,
      padding: { top: 32, right: 32, bottom: 32, left: 32 },
      margin: { top: 0, right: 0, bottom: 16, left: 0 },
      boxShadow: '0 4px 12px rgba(0,0,0,0.1)',
      opacity: 1,
      iconColor: '#059669',
      iconSize: 56,
      titleText: 'Order Confirmed!',
      titleTextCs: 'Objednavka potvrzena!',
      titleColor: '#059669',
      titleFontSize: 24,
      titleFontWeight: '700',
      titleAlignment: 'center',
      subtitleText: 'Thank you for your order. You will receive a confirmation email shortly.',
      subtitleTextCs: 'Dekujeme za objednavku. Potvrzovaci email obdrzite v kratce.',
      subtitleColor: '#374151',
      subtitleFontSize: 14,
      orderIdColor: '#6b7280',
      orderIdFontSize: 14,
      showOrderId: true,
      showEstimatedDelivery: true,
      showOrderSummary: true,
      titleFontFamily: 'inherit',
    },
    editableProperties: [
      ...COMMON_CONTAINER_PROPS.map((p) => ({
        ...p,
        default: p.key === 'backgroundColor' ? '#f0fdf4' :
          p.key === 'borderColor' ? '#bbf7d0' :
            p.key === 'borderRadius' ? 12 :
              p.key === 'padding' ? { top: 32, right: 32, bottom: 32, left: 32 } :
                p.key === 'boxShadow' ? '0 4px 12px rgba(0,0,0,0.1)' :
                  p.default,
      })),
      {
        key: 'iconColor',
        label: 'Icon Color',
        labelCs: 'Barva ikony',
        type: 'color',
        default: '#059669',
        group: 'icon',
      },
      {
        key: 'iconSize',
        label: 'Icon Size',
        labelCs: 'Velikost ikony',
        type: 'number',
        default: 56,
        min: 24,
        max: 96,
        unit: 'px',
        group: 'icon',
      },
      {
        key: 'titleText',
        label: 'Title Text',
        labelCs: 'Text nadpisu',
        type: 'text',
        default: 'Order Confirmed!',
        group: 'content',
      },
      {
        key: 'titleColor',
        label: 'Title Color',
        labelCs: 'Barva nadpisu',
        type: 'color',
        default: '#059669',
        group: 'typography',
      },
      {
        key: 'titleFontSize',
        label: 'Title Size',
        labelCs: 'Velikost nadpisu',
        type: 'number',
        default: 24,
        min: 16,
        max: 48,
        unit: 'px',
        group: 'typography',
      },
      {
        key: 'titleFontWeight',
        label: 'Title Weight',
        labelCs: 'Tucnost nadpisu',
        type: 'select',
        default: '700',
        options: [
          { value: '500', label: 'Medium', labelCs: 'Stredni' },
          { value: '600', label: 'Semi-bold', labelCs: 'Polotucny' },
          { value: '700', label: 'Bold', labelCs: 'Tucny' },
        ],
        group: 'typography',
      },
      {
        key: 'titleAlignment',
        label: 'Title Alignment',
        labelCs: 'Zarovnani nadpisu',
        type: 'select',
        default: 'center',
        options: [
          { value: 'left', label: 'Left', labelCs: 'Vlevo' },
          { value: 'center', label: 'Center', labelCs: 'Na stred' },
          { value: 'right', label: 'Right', labelCs: 'Vpravo' },
        ],
        group: 'typography',
      },
      {
        key: 'subtitleText',
        label: 'Subtitle Text',
        labelCs: 'Text podnadpisu',
        type: 'text',
        default: 'Thank you for your order.',
        group: 'content',
      },
      {
        key: 'subtitleColor',
        label: 'Subtitle Color',
        labelCs: 'Barva podnadpisu',
        type: 'color',
        default: '#374151',
        group: 'typography',
      },
      {
        key: 'subtitleFontSize',
        label: 'Subtitle Size',
        labelCs: 'Velikost podnadpisu',
        type: 'number',
        default: 14,
        min: 10,
        max: 24,
        unit: 'px',
        group: 'typography',
      },
      {
        key: 'orderIdColor',
        label: 'Order ID Color',
        labelCs: 'Barva cisla objednavky',
        type: 'color',
        default: '#6b7280',
        group: 'typography',
      },
      {
        key: 'showOrderId',
        label: 'Show Order ID',
        labelCs: 'Zobrazit cislo objednavky',
        type: 'boolean',
        default: true,
        group: 'content',
      },
      {
        key: 'showEstimatedDelivery',
        label: 'Show Delivery Estimate',
        labelCs: 'Zobrazit odhad doruceni',
        type: 'boolean',
        default: true,
        group: 'content',
      },
      {
        key: 'showOrderSummary',
        label: 'Show Summary',
        labelCs: 'Zobrazit souhrn',
        type: 'boolean',
        default: true,
        group: 'content',
      },
    ],
  },

  // -------------------------------------------------------------------------
  // NON-LOCKED calculator blocks (optional, user can add/remove)
  // -------------------------------------------------------------------------
  {
    id: 'coupon-input',
    name: 'Coupon Input',
    nameCs: 'Slevovy kod',
    category: 'calculator',
    step: 3,
    icon: 'Ticket',
    locked: false,
    canReposition: true,
    canRestyle: true,
    description: 'Promo/coupon code input field with apply button.',
    descriptionCs: 'Pole pro zadani slevoveho kodu s tlacitkem "Uplatnit".',
    defaultProps: {
      backgroundColor: '#ffffff',
      borderColor: '#e5e7eb',
      borderWidth: 1,
      borderStyle: 'solid',
      borderRadius: 8,
      padding: { top: 16, right: 16, bottom: 16, left: 16 },
      margin: { top: 0, right: 0, bottom: 12, left: 0 },
      boxShadow: 'none',
      opacity: 1,
      inputPlaceholder: 'Enter coupon code',
      inputPlaceholderCs: 'Zadejte slevovy kod',
      inputBorderColor: '#d1d5db',
      inputBorderRadius: 6,
      inputBackgroundColor: '#ffffff',
      applyButtonColor: '#3b82f6',
      applyButtonTextColor: '#ffffff',
      applyButtonText: 'Apply',
      applyButtonTextCs: 'Uplatnit',
      applyButtonRadius: 6,
      successColor: '#059669',
      errorColor: '#ef4444',
      labelFontSize: 14,
      labelColor: '#374151',
    },
    editableProperties: [
      ...COMMON_CONTAINER_PROPS.map((p) => ({
        ...p,
        default: p.key === 'padding' ? { top: 16, right: 16, bottom: 16, left: 16 } :
          p.key === 'margin' ? { top: 0, right: 0, bottom: 12, left: 0 } : p.default,
      })),
      {
        key: 'inputPlaceholder',
        label: 'Placeholder',
        labelCs: 'Zastupny text',
        type: 'text',
        default: 'Enter coupon code',
        group: 'content',
      },
      {
        key: 'inputBorderColor',
        label: 'Input Border',
        labelCs: 'Ramecek inputu',
        type: 'color',
        default: '#d1d5db',
        group: 'form',
      },
      {
        key: 'inputBorderRadius',
        label: 'Input Radius',
        labelCs: 'Zaobleni inputu',
        type: 'number',
        default: 6,
        min: 0,
        max: 16,
        unit: 'px',
        group: 'form',
      },
      {
        key: 'applyButtonColor',
        label: 'Button Color',
        labelCs: 'Barva tlacitka',
        type: 'color',
        default: '#3b82f6',
        group: 'button',
      },
      {
        key: 'applyButtonTextColor',
        label: 'Button Text Color',
        labelCs: 'Barva textu tlacitka',
        type: 'color',
        default: '#ffffff',
        group: 'button',
      },
      {
        key: 'applyButtonText',
        label: 'Button Text',
        labelCs: 'Text tlacitka',
        type: 'text',
        default: 'Apply',
        group: 'content',
      },
      {
        key: 'applyButtonRadius',
        label: 'Button Radius',
        labelCs: 'Zaobleni tlacitka',
        type: 'number',
        default: 6,
        min: 0,
        max: 16,
        unit: 'px',
        group: 'button',
      },
      {
        key: 'successColor',
        label: 'Success Color',
        labelCs: 'Barva uspechu',
        type: 'color',
        default: '#059669',
        group: 'feedback',
      },
      {
        key: 'errorColor',
        label: 'Error Color',
        labelCs: 'Barva chyby',
        type: 'color',
        default: '#ef4444',
        group: 'feedback',
      },
    ],
  },

  {
    id: 'express-tier',
    name: 'Express Processing',
    nameCs: 'Expresni zpracovani',
    category: 'calculator',
    step: 3,
    icon: 'Zap',
    locked: false,
    canReposition: true,
    canRestyle: true,
    description: 'Express/priority processing tier selector.',
    descriptionCs: 'Vyber urovne expresniho zpracovani.',
    defaultProps: {
      backgroundColor: '#fffbeb',
      borderColor: '#fcd34d',
      borderWidth: 1,
      borderStyle: 'solid',
      borderRadius: 8,
      padding: { top: 16, right: 16, bottom: 16, left: 16 },
      margin: { top: 0, right: 0, bottom: 12, left: 0 },
      boxShadow: 'none',
      opacity: 1,
      accentColor: '#f59e0b',
      labelColor: '#92400e',
      labelFontSize: 14,
      labelFontWeight: '600',
      optionBorderColor: '#fcd34d',
      optionBorderRadius: 8,
      optionBackgroundColor: '#ffffff',
      selectedOptionBorderColor: '#f59e0b',
      selectedOptionBackgroundColor: '#fffbeb',
      priceColor: '#92400e',
      priceFontSize: 16,
      priceFontWeight: '700',
      iconColor: '#f59e0b',
      showDescription: true,
      descriptionColor: '#a16207',
      descriptionFontSize: 12,
    },
    editableProperties: [
      ...COMMON_CONTAINER_PROPS.map((p) => ({
        ...p,
        default: p.key === 'backgroundColor' ? '#fffbeb' :
          p.key === 'borderColor' ? '#fcd34d' :
            p.key === 'padding' ? { top: 16, right: 16, bottom: 16, left: 16 } :
              p.key === 'margin' ? { top: 0, right: 0, bottom: 12, left: 0 } : p.default,
      })),
      {
        key: 'accentColor',
        label: 'Accent Color',
        labelCs: 'Akcentova barva',
        type: 'color',
        default: '#f59e0b',
        group: 'theme',
      },
      {
        key: 'labelColor',
        label: 'Label Color',
        labelCs: 'Barva popisku',
        type: 'color',
        default: '#92400e',
        group: 'typography',
      },
      {
        key: 'labelFontSize',
        label: 'Label Size',
        labelCs: 'Velikost popisku',
        type: 'number',
        default: 14,
        min: 10,
        max: 20,
        unit: 'px',
        group: 'typography',
      },
      {
        key: 'optionBorderColor',
        label: 'Option Border',
        labelCs: 'Ramecek moznosti',
        type: 'color',
        default: '#fcd34d',
        group: 'options',
      },
      {
        key: 'optionBorderRadius',
        label: 'Option Radius',
        labelCs: 'Zaobleni moznosti',
        type: 'number',
        default: 8,
        min: 0,
        max: 16,
        unit: 'px',
        group: 'options',
      },
      {
        key: 'selectedOptionBorderColor',
        label: 'Selected Border',
        labelCs: 'Ramecek vybrane',
        type: 'color',
        default: '#f59e0b',
        group: 'options',
      },
      {
        key: 'selectedOptionBackgroundColor',
        label: 'Selected Background',
        labelCs: 'Pozadi vybrane',
        type: 'color',
        default: '#fffbeb',
        group: 'options',
      },
      {
        key: 'priceColor',
        label: 'Price Color',
        labelCs: 'Barva ceny',
        type: 'color',
        default: '#92400e',
        group: 'pricing',
      },
      {
        key: 'priceFontSize',
        label: 'Price Size',
        labelCs: 'Velikost ceny',
        type: 'number',
        default: 16,
        min: 12,
        max: 28,
        unit: 'px',
        group: 'pricing',
      },
      {
        key: 'iconColor',
        label: 'Icon Color',
        labelCs: 'Barva ikony',
        type: 'color',
        default: '#f59e0b',
        group: 'icon',
      },
      {
        key: 'showDescription',
        label: 'Show Description',
        labelCs: 'Zobrazit popis',
        type: 'boolean',
        default: true,
        group: 'content',
      },
      {
        key: 'descriptionColor',
        label: 'Description Color',
        labelCs: 'Barva popisu',
        type: 'color',
        default: '#a16207',
        group: 'typography',
      },
    ],
  },

  {
    id: 'shipping-selector',
    name: 'Shipping Selector',
    nameCs: 'Vyber dopravy',
    category: 'calculator',
    step: 4,
    icon: 'Truck',
    locked: false,
    canReposition: true,
    canRestyle: true,
    description: 'Shipping method selector with prices and estimates.',
    descriptionCs: 'Vyber zpusobu dopravy s cenami a odhady doruceni.',
    defaultProps: {
      backgroundColor: '#ffffff',
      borderColor: '#e5e7eb',
      borderWidth: 1,
      borderStyle: 'solid',
      borderRadius: 8,
      padding: { top: 16, right: 16, bottom: 16, left: 16 },
      margin: { top: 0, right: 0, bottom: 12, left: 0 },
      boxShadow: 'none',
      opacity: 1,
      titleText: 'Shipping Method',
      titleTextCs: 'Zpusob dopravy',
      titleColor: '#111827',
      titleFontSize: 16,
      titleFontWeight: '600',
      optionBorderColor: '#e5e7eb',
      optionBorderRadius: 8,
      optionBackgroundColor: '#ffffff',
      optionHoverBackgroundColor: '#f9fafb',
      selectedOptionBorderColor: '#3b82f6',
      selectedOptionBackgroundColor: '#eff6ff',
      optionGap: 8,
      priceColor: '#374151',
      priceFontSize: 14,
      priceFontWeight: '600',
      estimateColor: '#6b7280',
      estimateFontSize: 12,
      iconColor: '#6b7280',
      iconSize: 20,
      showEstimate: true,
      showIcons: true,
    },
    editableProperties: [
      ...COMMON_CONTAINER_PROPS,
      {
        key: 'titleText',
        label: 'Title',
        labelCs: 'Nadpis',
        type: 'text',
        default: 'Shipping Method',
        group: 'content',
      },
      {
        key: 'titleColor',
        label: 'Title Color',
        labelCs: 'Barva nadpisu',
        type: 'color',
        default: '#111827',
        group: 'typography',
      },
      {
        key: 'titleFontSize',
        label: 'Title Size',
        labelCs: 'Velikost nadpisu',
        type: 'number',
        default: 16,
        min: 12,
        max: 28,
        unit: 'px',
        group: 'typography',
      },
      {
        key: 'optionBorderColor',
        label: 'Option Border',
        labelCs: 'Ramecek moznosti',
        type: 'color',
        default: '#e5e7eb',
        group: 'options',
      },
      {
        key: 'optionBorderRadius',
        label: 'Option Radius',
        labelCs: 'Zaobleni moznosti',
        type: 'number',
        default: 8,
        min: 0,
        max: 16,
        unit: 'px',
        group: 'options',
      },
      {
        key: 'selectedOptionBorderColor',
        label: 'Selected Border',
        labelCs: 'Ramecek vybrane',
        type: 'color',
        default: '#3b82f6',
        group: 'options',
      },
      {
        key: 'selectedOptionBackgroundColor',
        label: 'Selected Background',
        labelCs: 'Pozadi vybrane',
        type: 'color',
        default: '#eff6ff',
        group: 'options',
      },
      {
        key: 'optionGap',
        label: 'Option Gap',
        labelCs: 'Mezera mezi moznostmi',
        type: 'number',
        default: 8,
        min: 0,
        max: 24,
        unit: 'px',
        group: 'layout',
      },
      {
        key: 'priceColor',
        label: 'Price Color',
        labelCs: 'Barva ceny',
        type: 'color',
        default: '#374151',
        group: 'pricing',
      },
      {
        key: 'estimateColor',
        label: 'Estimate Color',
        labelCs: 'Barva odhadu',
        type: 'color',
        default: '#6b7280',
        group: 'typography',
      },
      {
        key: 'iconColor',
        label: 'Icon Color',
        labelCs: 'Barva ikony',
        type: 'color',
        default: '#6b7280',
        group: 'icon',
      },
      {
        key: 'showEstimate',
        label: 'Show Estimate',
        labelCs: 'Zobrazit odhad',
        type: 'boolean',
        default: true,
        group: 'content',
      },
      {
        key: 'showIcons',
        label: 'Show Icons',
        labelCs: 'Zobrazit ikony',
        type: 'boolean',
        default: true,
        group: 'content',
      },
    ],
  },

  {
    id: 'upsell-panel',
    name: 'Upsell Panel',
    nameCs: 'Panel doporuceni',
    category: 'calculator',
    step: 3,
    icon: 'Sparkles',
    locked: false,
    canReposition: true,
    canRestyle: true,
    description: 'Upsell recommendations for additional services or upgrades.',
    descriptionCs: 'Doporuceni dalsich sluzeb nebo upgradu.',
    defaultProps: {
      backgroundColor: '#faf5ff',
      borderColor: '#d8b4fe',
      borderWidth: 1,
      borderStyle: 'solid',
      borderRadius: 8,
      padding: { top: 16, right: 16, bottom: 16, left: 16 },
      margin: { top: 0, right: 0, bottom: 12, left: 0 },
      boxShadow: 'none',
      opacity: 1,
      titleText: 'Recommended',
      titleTextCs: 'Doporucujeme',
      titleColor: '#7c3aed',
      titleFontSize: 14,
      titleFontWeight: '600',
      itemBackgroundColor: '#ffffff',
      itemBorderColor: '#e9d5ff',
      itemBorderRadius: 8,
      itemPadding: { top: 12, right: 12, bottom: 12, left: 12 },
      itemGap: 8,
      itemNameColor: '#374151',
      itemNameFontSize: 14,
      itemPriceColor: '#7c3aed',
      itemPriceFontSize: 14,
      itemPriceFontWeight: '600',
      itemDescriptionColor: '#6b7280',
      itemDescriptionFontSize: 12,
      addButtonColor: '#7c3aed',
      addButtonTextColor: '#ffffff',
      addButtonRadius: 6,
      showDescriptions: true,
    },
    editableProperties: [
      ...COMMON_CONTAINER_PROPS.map((p) => ({
        ...p,
        default: p.key === 'backgroundColor' ? '#faf5ff' :
          p.key === 'borderColor' ? '#d8b4fe' :
            p.key === 'padding' ? { top: 16, right: 16, bottom: 16, left: 16 } :
              p.key === 'margin' ? { top: 0, right: 0, bottom: 12, left: 0 } : p.default,
      })),
      {
        key: 'titleText',
        label: 'Title',
        labelCs: 'Nadpis',
        type: 'text',
        default: 'Recommended',
        group: 'content',
      },
      {
        key: 'titleColor',
        label: 'Title Color',
        labelCs: 'Barva nadpisu',
        type: 'color',
        default: '#7c3aed',
        group: 'typography',
      },
      {
        key: 'titleFontSize',
        label: 'Title Size',
        labelCs: 'Velikost nadpisu',
        type: 'number',
        default: 14,
        min: 10,
        max: 24,
        unit: 'px',
        group: 'typography',
      },
      {
        key: 'itemBackgroundColor',
        label: 'Item Background',
        labelCs: 'Pozadi polozky',
        type: 'color',
        default: '#ffffff',
        group: 'items',
      },
      {
        key: 'itemBorderColor',
        label: 'Item Border',
        labelCs: 'Ramecek polozky',
        type: 'color',
        default: '#e9d5ff',
        group: 'items',
      },
      {
        key: 'itemBorderRadius',
        label: 'Item Radius',
        labelCs: 'Zaobleni polozky',
        type: 'number',
        default: 8,
        min: 0,
        max: 16,
        unit: 'px',
        group: 'items',
      },
      {
        key: 'itemGap',
        label: 'Item Gap',
        labelCs: 'Mezera mezi polozkami',
        type: 'number',
        default: 8,
        min: 0,
        max: 24,
        unit: 'px',
        group: 'layout',
      },
      {
        key: 'itemNameColor',
        label: 'Item Name Color',
        labelCs: 'Barva nazvu',
        type: 'color',
        default: '#374151',
        group: 'items',
      },
      {
        key: 'itemPriceColor',
        label: 'Price Color',
        labelCs: 'Barva ceny',
        type: 'color',
        default: '#7c3aed',
        group: 'items',
      },
      {
        key: 'itemDescriptionColor',
        label: 'Description Color',
        labelCs: 'Barva popisu',
        type: 'color',
        default: '#6b7280',
        group: 'items',
      },
      {
        key: 'addButtonColor',
        label: 'Add Button Color',
        labelCs: 'Barva tlacitka pridani',
        type: 'color',
        default: '#7c3aed',
        group: 'button',
      },
      {
        key: 'addButtonTextColor',
        label: 'Add Button Text',
        labelCs: 'Barva textu tlacitka',
        type: 'color',
        default: '#ffffff',
        group: 'button',
      },
      {
        key: 'addButtonRadius',
        label: 'Add Button Radius',
        labelCs: 'Zaobleni tlacitka',
        type: 'number',
        default: 6,
        min: 0,
        max: 16,
        unit: 'px',
        group: 'button',
      },
      {
        key: 'showDescriptions',
        label: 'Show Descriptions',
        labelCs: 'Zobrazit popisy',
        type: 'boolean',
        default: true,
        group: 'content',
      },
    ],
  },

  {
    id: 'promo-bar',
    name: 'Promo Bar',
    nameCs: 'Promo lista',
    category: 'calculator',
    step: null, // can appear in any step
    icon: 'Megaphone',
    locked: false,
    canReposition: true,
    canRestyle: true,
    description: 'Promotional banner with customizable message.',
    descriptionCs: 'Propagacni lista s upravitelnou zpravou.',
    defaultProps: {
      backgroundColor: '#eef2ff',
      borderColor: '#c7d2fe',
      borderWidth: 1,
      borderStyle: 'solid',
      borderRadius: 8,
      padding: { top: 12, right: 16, bottom: 12, left: 16 },
      margin: { top: 0, right: 0, bottom: 12, left: 0 },
      boxShadow: 'none',
      opacity: 1,
      text: 'Free shipping on orders over 1000 CZK!',
      textCs: 'Doprava zdarma pri objednavce nad 1000 Kc!',
      textColor: '#3730a3',
      textFontSize: 14,
      textFontWeight: '500',
      textAlignment: 'center',
      iconName: 'Megaphone',
      iconColor: '#4f46e5',
      iconSize: 18,
      showIcon: true,
      showDismiss: true,
      dismissColor: '#6366f1',
    },
    editableProperties: [
      ...COMMON_CONTAINER_PROPS.map((p) => ({
        ...p,
        default: p.key === 'backgroundColor' ? '#eef2ff' :
          p.key === 'borderColor' ? '#c7d2fe' :
            p.key === 'padding' ? { top: 12, right: 16, bottom: 12, left: 16 } :
              p.key === 'margin' ? { top: 0, right: 0, bottom: 12, left: 0 } : p.default,
      })),
      {
        key: 'text',
        label: 'Promo Text',
        labelCs: 'Text promo',
        type: 'text',
        default: 'Free shipping on orders over 1000 CZK!',
        group: 'content',
      },
      {
        key: 'textColor',
        label: 'Text Color',
        labelCs: 'Barva textu',
        type: 'color',
        default: '#3730a3',
        group: 'typography',
      },
      {
        key: 'textFontSize',
        label: 'Text Size',
        labelCs: 'Velikost textu',
        type: 'number',
        default: 14,
        min: 10,
        max: 24,
        unit: 'px',
        group: 'typography',
      },
      {
        key: 'textFontWeight',
        label: 'Text Weight',
        labelCs: 'Tucnost textu',
        type: 'select',
        default: '500',
        options: [
          { value: '400', label: 'Normal', labelCs: 'Normalni' },
          { value: '500', label: 'Medium', labelCs: 'Stredni' },
          { value: '600', label: 'Semi-bold', labelCs: 'Polotucny' },
          { value: '700', label: 'Bold', labelCs: 'Tucny' },
        ],
        group: 'typography',
      },
      {
        key: 'textAlignment',
        label: 'Text Alignment',
        labelCs: 'Zarovnani textu',
        type: 'select',
        default: 'center',
        options: [
          { value: 'left', label: 'Left', labelCs: 'Vlevo' },
          { value: 'center', label: 'Center', labelCs: 'Na stred' },
          { value: 'right', label: 'Right', labelCs: 'Vpravo' },
        ],
        group: 'typography',
      },
      {
        key: 'iconColor',
        label: 'Icon Color',
        labelCs: 'Barva ikony',
        type: 'color',
        default: '#4f46e5',
        group: 'icon',
      },
      {
        key: 'iconSize',
        label: 'Icon Size',
        labelCs: 'Velikost ikony',
        type: 'number',
        default: 18,
        min: 12,
        max: 32,
        unit: 'px',
        group: 'icon',
      },
      {
        key: 'showIcon',
        label: 'Show Icon',
        labelCs: 'Zobrazit ikonu',
        type: 'boolean',
        default: true,
        group: 'content',
      },
      {
        key: 'showDismiss',
        label: 'Show Dismiss',
        labelCs: 'Zobrazit zavreni',
        type: 'boolean',
        default: true,
        group: 'content',
      },
      {
        key: 'dismissColor',
        label: 'Dismiss Color',
        labelCs: 'Barva zavreni',
        type: 'color',
        default: '#6366f1',
        group: 'icon',
      },
    ],
  },

  {
    id: 'shopify-cart-button',
    name: 'Shopify Cart Button',
    nameCs: 'Shopify tlacitko kosiku',
    category: 'calculator',
    step: 3,
    icon: 'ShoppingCart',
    locked: false,
    canReposition: true,
    canRestyle: true,
    description: 'Add-to-cart button for Shopify integration.',
    descriptionCs: 'Tlacitko pro pridani do kosiku pres Shopify integraci.',
    defaultProps: {
      backgroundColor: '#000000',
      borderColor: '#000000',
      borderWidth: 0,
      borderStyle: 'none',
      borderRadius: 8,
      padding: { top: 14, right: 28, bottom: 14, left: 28 },
      margin: { top: 8, right: 0, bottom: 8, left: 0 },
      boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
      opacity: 1,
      buttonText: 'Add to Cart',
      buttonTextCs: 'Pridat do kosiku',
      textColor: '#ffffff',
      textFontSize: 16,
      textFontWeight: '600',
      hoverBackgroundColor: '#1a1a1a',
      iconColor: '#ffffff',
      iconSize: 20,
      showIcon: true,
      iconPosition: 'left',
      fullWidth: true,
      loadingText: 'Adding...',
      loadingTextCs: 'Pridavam...',
      successText: 'Added!',
      successTextCs: 'Pridano!',
      successBackgroundColor: '#059669',
      disabledBackgroundColor: '#9ca3af',
      disabledTextColor: '#ffffff',
    },
    editableProperties: [
      ...COMMON_CONTAINER_PROPS.map((p) => ({
        ...p,
        default: p.key === 'backgroundColor' ? '#000000' :
          p.key === 'borderColor' ? '#000000' :
            p.key === 'borderWidth' ? 0 :
              p.key === 'borderStyle' ? 'none' :
                p.key === 'padding' ? { top: 14, right: 28, bottom: 14, left: 28 } :
                  p.key === 'margin' ? { top: 8, right: 0, bottom: 8, left: 0 } :
                    p.key === 'boxShadow' ? '0 1px 3px rgba(0,0,0,0.1)' : p.default,
      })),
      {
        key: 'buttonText',
        label: 'Button Text',
        labelCs: 'Text tlacitka',
        type: 'text',
        default: 'Add to Cart',
        group: 'content',
      },
      {
        key: 'textColor',
        label: 'Text Color',
        labelCs: 'Barva textu',
        type: 'color',
        default: '#ffffff',
        group: 'typography',
      },
      {
        key: 'textFontSize',
        label: 'Text Size',
        labelCs: 'Velikost textu',
        type: 'number',
        default: 16,
        min: 12,
        max: 24,
        unit: 'px',
        group: 'typography',
      },
      {
        key: 'textFontWeight',
        label: 'Text Weight',
        labelCs: 'Tucnost textu',
        type: 'select',
        default: '600',
        options: [
          { value: '400', label: 'Normal', labelCs: 'Normalni' },
          { value: '500', label: 'Medium', labelCs: 'Stredni' },
          { value: '600', label: 'Semi-bold', labelCs: 'Polotucny' },
          { value: '700', label: 'Bold', labelCs: 'Tucny' },
        ],
        group: 'typography',
      },
      {
        key: 'hoverBackgroundColor',
        label: 'Hover Background',
        labelCs: 'Pozadi pri navrhu',
        type: 'color',
        default: '#1a1a1a',
        group: 'interaction',
      },
      {
        key: 'iconColor',
        label: 'Icon Color',
        labelCs: 'Barva ikony',
        type: 'color',
        default: '#ffffff',
        group: 'icon',
      },
      {
        key: 'showIcon',
        label: 'Show Icon',
        labelCs: 'Zobrazit ikonu',
        type: 'boolean',
        default: true,
        group: 'content',
      },
      {
        key: 'iconPosition',
        label: 'Icon Position',
        labelCs: 'Pozice ikony',
        type: 'select',
        default: 'left',
        options: [
          { value: 'left', label: 'Left', labelCs: 'Vlevo' },
          { value: 'right', label: 'Right', labelCs: 'Vpravo' },
        ],
        group: 'icon',
      },
      {
        key: 'fullWidth',
        label: 'Full Width',
        labelCs: 'Plna sirka',
        type: 'boolean',
        default: true,
        group: 'layout',
      },
      {
        key: 'successBackgroundColor',
        label: 'Success Color',
        labelCs: 'Barva uspechu',
        type: 'color',
        default: '#059669',
        group: 'feedback',
      },
      {
        key: 'disabledBackgroundColor',
        label: 'Disabled Color',
        labelCs: 'Barva disabled',
        type: 'color',
        default: '#9ca3af',
        group: 'feedback',
      },
    ],
  },
];
