/**
 * contentBlocks.js -- Content block definitions for the Widget Builder.
 *
 * Content blocks display text, images, buttons, badges, icons, alerts,
 * and lists. They carry no functional calculator logic -- they are
 * purely visual and informational.
 */

export const contentBlocks = [
  // -------------------------------------------------------------------------
  // Heading
  // -------------------------------------------------------------------------
  {
    id: 'heading',
    name: 'Heading',
    nameCs: 'Nadpis',
    category: 'content',
    step: null,
    icon: 'Heading',
    locked: false,
    canReposition: true,
    canRestyle: true,
    description: 'Heading text from H1 to H6.',
    descriptionCs: 'Nadpis textu od H1 po H6.',
    defaultProps: {
      text: 'Your Heading',
      textCs: 'Vas nadpis',
      level: 'h2',
      color: '#111827',
      fontSize: 24,
      fontWeight: '700',
      fontFamily: 'inherit',
      textAlignment: 'left',
      lineHeight: 1.3,
      letterSpacing: 0,
      textTransform: 'none',
      textDecoration: 'none',
      margin: { top: 0, right: 0, bottom: 12, left: 0 },
      padding: { top: 0, right: 0, bottom: 0, left: 0 },
      opacity: 1,
    },
    editableProperties: [
      {
        key: 'text',
        label: 'Text',
        labelCs: 'Text',
        type: 'text',
        default: 'Your Heading',
        group: 'content',
      },
      {
        key: 'level',
        label: 'Level',
        labelCs: 'Uroven',
        type: 'select',
        default: 'h2',
        options: [
          { value: 'h1', label: 'H1', labelCs: 'H1' },
          { value: 'h2', label: 'H2', labelCs: 'H2' },
          { value: 'h3', label: 'H3', labelCs: 'H3' },
          { value: 'h4', label: 'H4', labelCs: 'H4' },
          { value: 'h5', label: 'H5', labelCs: 'H5' },
          { value: 'h6', label: 'H6', labelCs: 'H6' },
        ],
        group: 'content',
      },
      {
        key: 'color',
        label: 'Color',
        labelCs: 'Barva',
        type: 'color',
        default: '#111827',
        group: 'typography',
      },
      {
        key: 'fontSize',
        label: 'Font Size',
        labelCs: 'Velikost fontu',
        type: 'number',
        default: 24,
        min: 10,
        max: 72,
        unit: 'px',
        group: 'typography',
      },
      {
        key: 'fontWeight',
        label: 'Font Weight',
        labelCs: 'Tucnost',
        type: 'select',
        default: '700',
        options: [
          { value: '300', label: 'Light', labelCs: 'Tenky' },
          { value: '400', label: 'Normal', labelCs: 'Normalni' },
          { value: '500', label: 'Medium', labelCs: 'Stredni' },
          { value: '600', label: 'Semi-bold', labelCs: 'Polotucny' },
          { value: '700', label: 'Bold', labelCs: 'Tucny' },
          { value: '800', label: 'Extra-bold', labelCs: 'Extra tucny' },
          { value: '900', label: 'Black', labelCs: 'Cerny' },
        ],
        group: 'typography',
      },
      {
        key: 'fontFamily',
        label: 'Font Family',
        labelCs: 'Rodina fontu',
        type: 'font',
        default: 'inherit',
        group: 'typography',
      },
      {
        key: 'textAlignment',
        label: 'Alignment',
        labelCs: 'Zarovnani',
        type: 'select',
        default: 'left',
        options: [
          { value: 'left', label: 'Left', labelCs: 'Vlevo' },
          { value: 'center', label: 'Center', labelCs: 'Na stred' },
          { value: 'right', label: 'Right', labelCs: 'Vpravo' },
        ],
        group: 'typography',
      },
      {
        key: 'lineHeight',
        label: 'Line Height',
        labelCs: 'Vyska radku',
        type: 'number',
        default: 1.3,
        min: 0.8,
        max: 3,
        step: 0.1,
        group: 'typography',
      },
      {
        key: 'letterSpacing',
        label: 'Letter Spacing',
        labelCs: 'Proklad pismen',
        type: 'number',
        default: 0,
        min: -2,
        max: 10,
        step: 0.5,
        unit: 'px',
        group: 'typography',
      },
      {
        key: 'textTransform',
        label: 'Transform',
        labelCs: 'Transformace textu',
        type: 'select',
        default: 'none',
        options: [
          { value: 'none', label: 'None', labelCs: 'Zadna' },
          { value: 'uppercase', label: 'Uppercase', labelCs: 'Velka pismena' },
          { value: 'lowercase', label: 'Lowercase', labelCs: 'Mala pismena' },
          { value: 'capitalize', label: 'Capitalize', labelCs: 'Prvni velke' },
        ],
        group: 'typography',
      },
      {
        key: 'textDecoration',
        label: 'Decoration',
        labelCs: 'Dekorace textu',
        type: 'select',
        default: 'none',
        options: [
          { value: 'none', label: 'None', labelCs: 'Zadna' },
          { value: 'underline', label: 'Underline', labelCs: 'Podtrzeni' },
          { value: 'line-through', label: 'Strikethrough', labelCs: 'Preskrtnuti' },
        ],
        group: 'typography',
      },
      {
        key: 'margin',
        label: 'Margin',
        labelCs: 'Vnejsi odsazeni',
        type: 'spacing',
        default: { top: 0, right: 0, bottom: 12, left: 0 },
        group: 'container',
      },
      {
        key: 'padding',
        label: 'Padding',
        labelCs: 'Vnitrni odsazeni',
        type: 'spacing',
        default: { top: 0, right: 0, bottom: 0, left: 0 },
        group: 'container',
      },
      {
        key: 'opacity',
        label: 'Opacity',
        labelCs: 'Pruhlednost',
        type: 'number',
        default: 1,
        min: 0,
        max: 1,
        step: 0.05,
        group: 'container',
      },
    ],
  },

  // -------------------------------------------------------------------------
  // Text (Paragraph)
  // -------------------------------------------------------------------------
  {
    id: 'text',
    name: 'Text',
    nameCs: 'Text',
    category: 'content',
    step: null,
    icon: 'Type',
    locked: false,
    canReposition: true,
    canRestyle: true,
    description: 'Paragraph text block with formatting options.',
    descriptionCs: 'Odstavcovy textovy blok s moznostmi formatovani.',
    defaultProps: {
      content: 'Your text here...',
      contentCs: 'Vas text zde...',
      color: '#374151',
      fontSize: 14,
      fontWeight: '400',
      fontFamily: 'inherit',
      textAlignment: 'left',
      lineHeight: 1.6,
      letterSpacing: 0,
      textTransform: 'none',
      backgroundColor: 'transparent',
      borderRadius: 0,
      padding: { top: 0, right: 0, bottom: 0, left: 0 },
      margin: { top: 0, right: 0, bottom: 12, left: 0 },
      opacity: 1,
      maxWidth: 'none',
    },
    editableProperties: [
      {
        key: 'content',
        label: 'Content',
        labelCs: 'Obsah',
        type: 'text',
        default: 'Your text here...',
        group: 'content',
      },
      {
        key: 'color',
        label: 'Color',
        labelCs: 'Barva',
        type: 'color',
        default: '#374151',
        group: 'typography',
      },
      {
        key: 'fontSize',
        label: 'Font Size',
        labelCs: 'Velikost fontu',
        type: 'number',
        default: 14,
        min: 10,
        max: 36,
        unit: 'px',
        group: 'typography',
      },
      {
        key: 'fontWeight',
        label: 'Font Weight',
        labelCs: 'Tucnost',
        type: 'select',
        default: '400',
        options: [
          { value: '300', label: 'Light', labelCs: 'Tenky' },
          { value: '400', label: 'Normal', labelCs: 'Normalni' },
          { value: '500', label: 'Medium', labelCs: 'Stredni' },
          { value: '600', label: 'Semi-bold', labelCs: 'Polotucny' },
          { value: '700', label: 'Bold', labelCs: 'Tucny' },
        ],
        group: 'typography',
      },
      {
        key: 'fontFamily',
        label: 'Font Family',
        labelCs: 'Rodina fontu',
        type: 'font',
        default: 'inherit',
        group: 'typography',
      },
      {
        key: 'textAlignment',
        label: 'Alignment',
        labelCs: 'Zarovnani',
        type: 'select',
        default: 'left',
        options: [
          { value: 'left', label: 'Left', labelCs: 'Vlevo' },
          { value: 'center', label: 'Center', labelCs: 'Na stred' },
          { value: 'right', label: 'Right', labelCs: 'Vpravo' },
          { value: 'justify', label: 'Justify', labelCs: 'Do bloku' },
        ],
        group: 'typography',
      },
      {
        key: 'lineHeight',
        label: 'Line Height',
        labelCs: 'Vyska radku',
        type: 'number',
        default: 1.6,
        min: 1,
        max: 3,
        step: 0.1,
        group: 'typography',
      },
      {
        key: 'letterSpacing',
        label: 'Letter Spacing',
        labelCs: 'Proklad pismen',
        type: 'number',
        default: 0,
        min: -2,
        max: 10,
        step: 0.5,
        unit: 'px',
        group: 'typography',
      },
      {
        key: 'textTransform',
        label: 'Transform',
        labelCs: 'Transformace textu',
        type: 'select',
        default: 'none',
        options: [
          { value: 'none', label: 'None', labelCs: 'Zadna' },
          { value: 'uppercase', label: 'Uppercase', labelCs: 'Velka pismena' },
          { value: 'lowercase', label: 'Lowercase', labelCs: 'Mala pismena' },
          { value: 'capitalize', label: 'Capitalize', labelCs: 'Prvni velke' },
        ],
        group: 'typography',
      },
      {
        key: 'backgroundColor',
        label: 'Background',
        labelCs: 'Pozadi',
        type: 'color',
        default: 'transparent',
        group: 'container',
      },
      {
        key: 'borderRadius',
        label: 'Corner Radius',
        labelCs: 'Zaobleni rohu',
        type: 'number',
        default: 0,
        min: 0,
        max: 24,
        unit: 'px',
        group: 'container',
      },
      {
        key: 'padding',
        label: 'Padding',
        labelCs: 'Vnitrni odsazeni',
        type: 'spacing',
        default: { top: 0, right: 0, bottom: 0, left: 0 },
        group: 'container',
      },
      {
        key: 'margin',
        label: 'Margin',
        labelCs: 'Vnejsi odsazeni',
        type: 'spacing',
        default: { top: 0, right: 0, bottom: 12, left: 0 },
        group: 'container',
      },
      {
        key: 'opacity',
        label: 'Opacity',
        labelCs: 'Pruhlednost',
        type: 'number',
        default: 1,
        min: 0,
        max: 1,
        step: 0.05,
        group: 'container',
      },
    ],
  },

  // -------------------------------------------------------------------------
  // Image
  // -------------------------------------------------------------------------
  {
    id: 'image',
    name: 'Image',
    nameCs: 'Obrazek',
    category: 'content',
    step: null,
    icon: 'Image',
    locked: false,
    canReposition: true,
    canRestyle: true,
    description: 'Image with configurable size, alignment and border.',
    descriptionCs: 'Obrazek s nastavitelnou velikosti, zarovnanim a rameckem.',
    defaultProps: {
      src: '',
      alt: '',
      altCs: '',
      width: 'auto',
      maxWidth: '100%',
      height: 'auto',
      objectFit: 'cover',
      borderRadius: 8,
      borderColor: 'transparent',
      borderWidth: 0,
      borderStyle: 'none',
      boxShadow: 'none',
      opacity: 1,
      alignment: 'center',
      margin: { top: 0, right: 0, bottom: 12, left: 0 },
      padding: { top: 0, right: 0, bottom: 0, left: 0 },
    },
    editableProperties: [
      {
        key: 'src',
        label: 'Image URL',
        labelCs: 'URL obrazku',
        type: 'text',
        default: '',
        group: 'content',
      },
      {
        key: 'alt',
        label: 'Alt Text',
        labelCs: 'Alternativni text',
        type: 'text',
        default: '',
        group: 'content',
      },
      {
        key: 'width',
        label: 'Width',
        labelCs: 'Sirka',
        type: 'select',
        default: 'auto',
        options: [
          { value: 'auto', label: 'Auto', labelCs: 'Automaticka' },
          { value: '25%', label: '25%', labelCs: '25%' },
          { value: '50%', label: '50%', labelCs: '50%' },
          { value: '75%', label: '75%', labelCs: '75%' },
          { value: '100%', label: '100%', labelCs: '100%' },
        ],
        group: 'dimensions',
      },
      {
        key: 'maxWidth',
        label: 'Max Width',
        labelCs: 'Maximalni sirka',
        type: 'select',
        default: '100%',
        options: [
          { value: '100%', label: '100%', labelCs: '100%' },
          { value: '480px', label: '480px', labelCs: '480px' },
          { value: '320px', label: '320px', labelCs: '320px' },
          { value: '200px', label: '200px', labelCs: '200px' },
        ],
        group: 'dimensions',
      },
      {
        key: 'height',
        label: 'Height',
        labelCs: 'Vyska',
        type: 'select',
        default: 'auto',
        options: [
          { value: 'auto', label: 'Auto', labelCs: 'Automaticka' },
          { value: '100px', label: '100px', labelCs: '100px' },
          { value: '200px', label: '200px', labelCs: '200px' },
          { value: '300px', label: '300px', labelCs: '300px' },
          { value: '400px', label: '400px', labelCs: '400px' },
        ],
        group: 'dimensions',
      },
      {
        key: 'objectFit',
        label: 'Object Fit',
        labelCs: 'Prizpusobeni',
        type: 'select',
        default: 'cover',
        options: [
          { value: 'cover', label: 'Cover', labelCs: 'Pokryti' },
          { value: 'contain', label: 'Contain', labelCs: 'Vejit se' },
          { value: 'fill', label: 'Fill', labelCs: 'Vyplnit' },
          { value: 'none', label: 'None', labelCs: 'Zadne' },
        ],
        group: 'dimensions',
      },
      {
        key: 'borderRadius',
        label: 'Corner Radius',
        labelCs: 'Zaobleni rohu',
        type: 'number',
        default: 8,
        min: 0,
        max: 50,
        unit: 'px',
        group: 'container',
      },
      {
        key: 'borderColor',
        label: 'Border Color',
        labelCs: 'Barva ramecku',
        type: 'color',
        default: 'transparent',
        group: 'container',
      },
      {
        key: 'borderWidth',
        label: 'Border Width',
        labelCs: 'Sirka ramecku',
        type: 'number',
        default: 0,
        min: 0,
        max: 8,
        unit: 'px',
        group: 'container',
      },
      {
        key: 'boxShadow',
        label: 'Shadow',
        labelCs: 'Stin',
        type: 'shadow',
        default: 'none',
        options: [
          { value: 'none', label: 'None', labelCs: 'Zadny' },
          { value: '0 1px 3px rgba(0,0,0,0.1)', label: 'Small', labelCs: 'Maly' },
          { value: '0 4px 12px rgba(0,0,0,0.1)', label: 'Medium', labelCs: 'Stredni' },
          { value: '0 8px 24px rgba(0,0,0,0.12)', label: 'Large', labelCs: 'Velky' },
        ],
        group: 'container',
      },
      {
        key: 'opacity',
        label: 'Opacity',
        labelCs: 'Pruhlednost',
        type: 'number',
        default: 1,
        min: 0,
        max: 1,
        step: 0.05,
        group: 'container',
      },
      {
        key: 'alignment',
        label: 'Alignment',
        labelCs: 'Zarovnani',
        type: 'select',
        default: 'center',
        options: [
          { value: 'left', label: 'Left', labelCs: 'Vlevo' },
          { value: 'center', label: 'Center', labelCs: 'Na stred' },
          { value: 'right', label: 'Right', labelCs: 'Vpravo' },
        ],
        group: 'layout',
      },
      {
        key: 'margin',
        label: 'Margin',
        labelCs: 'Vnejsi odsazeni',
        type: 'spacing',
        default: { top: 0, right: 0, bottom: 12, left: 0 },
        group: 'container',
      },
    ],
  },

  // -------------------------------------------------------------------------
  // Button
  // -------------------------------------------------------------------------
  {
    id: 'button',
    name: 'Button',
    nameCs: 'Tlacitko',
    category: 'content',
    step: null,
    icon: 'MousePointerClick',
    locked: false,
    canReposition: true,
    canRestyle: true,
    description: 'Styled button with customizable text, colors, and size.',
    descriptionCs: 'Stylizovane tlacitko s upravitelnym textem, barvami a velikosti.',
    defaultProps: {
      text: 'Click Me',
      textCs: 'Kliknete sem',
      backgroundColor: '#3b82f6',
      textColor: '#ffffff',
      fontSize: 14,
      fontWeight: '600',
      fontFamily: 'inherit',
      borderRadius: 8,
      borderColor: '#3b82f6',
      borderWidth: 0,
      borderStyle: 'none',
      padding: { top: 10, right: 20, bottom: 10, left: 20 },
      margin: { top: 0, right: 0, bottom: 12, left: 0 },
      boxShadow: 'none',
      opacity: 1,
      hoverBackgroundColor: '#2563eb',
      hoverTextColor: '#ffffff',
      textAlignment: 'center',
      fullWidth: false,
      cursor: 'pointer',
      textTransform: 'none',
      letterSpacing: 0,
      iconName: '',
      iconPosition: 'left',
      iconSize: 16,
    },
    editableProperties: [
      {
        key: 'text',
        label: 'Text',
        labelCs: 'Text',
        type: 'text',
        default: 'Click Me',
        group: 'content',
      },
      {
        key: 'backgroundColor',
        label: 'Background',
        labelCs: 'Pozadi',
        type: 'color',
        default: '#3b82f6',
        group: 'container',
      },
      {
        key: 'textColor',
        label: 'Text Color',
        labelCs: 'Barva textu',
        type: 'color',
        default: '#ffffff',
        group: 'typography',
      },
      {
        key: 'fontSize',
        label: 'Font Size',
        labelCs: 'Velikost fontu',
        type: 'number',
        default: 14,
        min: 10,
        max: 28,
        unit: 'px',
        group: 'typography',
      },
      {
        key: 'fontWeight',
        label: 'Font Weight',
        labelCs: 'Tucnost',
        type: 'select',
        default: '600',
        options: [
          { value: '400', label: 'Normal', labelCs: 'Normalni' },
          { value: '500', label: 'Medium', labelCs: 'Stredni' },
          { value: '600', label: 'Semi-bold', labelCs: 'Polotucny' },
          { value: '700', label: 'Bold', labelCs: 'Tucny' },
        ],
        group: 'typography',
      },
      {
        key: 'fontFamily',
        label: 'Font Family',
        labelCs: 'Rodina fontu',
        type: 'font',
        default: 'inherit',
        group: 'typography',
      },
      {
        key: 'borderRadius',
        label: 'Corner Radius',
        labelCs: 'Zaobleni rohu',
        type: 'number',
        default: 8,
        min: 0,
        max: 50,
        unit: 'px',
        group: 'container',
      },
      {
        key: 'borderColor',
        label: 'Border Color',
        labelCs: 'Barva ramecku',
        type: 'color',
        default: '#3b82f6',
        group: 'container',
      },
      {
        key: 'borderWidth',
        label: 'Border Width',
        labelCs: 'Sirka ramecku',
        type: 'number',
        default: 0,
        min: 0,
        max: 4,
        unit: 'px',
        group: 'container',
      },
      {
        key: 'padding',
        label: 'Padding',
        labelCs: 'Vnitrni odsazeni',
        type: 'spacing',
        default: { top: 10, right: 20, bottom: 10, left: 20 },
        group: 'container',
      },
      {
        key: 'margin',
        label: 'Margin',
        labelCs: 'Vnejsi odsazeni',
        type: 'spacing',
        default: { top: 0, right: 0, bottom: 12, left: 0 },
        group: 'container',
      },
      {
        key: 'boxShadow',
        label: 'Shadow',
        labelCs: 'Stin',
        type: 'shadow',
        default: 'none',
        options: [
          { value: 'none', label: 'None', labelCs: 'Zadny' },
          { value: '0 1px 3px rgba(0,0,0,0.1)', label: 'Small', labelCs: 'Maly' },
          { value: '0 4px 12px rgba(0,0,0,0.15)', label: 'Medium', labelCs: 'Stredni' },
        ],
        group: 'container',
      },
      {
        key: 'opacity',
        label: 'Opacity',
        labelCs: 'Pruhlednost',
        type: 'number',
        default: 1,
        min: 0,
        max: 1,
        step: 0.05,
        group: 'container',
      },
      {
        key: 'hoverBackgroundColor',
        label: 'Hover Background',
        labelCs: 'Pozadi pri navrhu',
        type: 'color',
        default: '#2563eb',
        group: 'interaction',
      },
      {
        key: 'hoverTextColor',
        label: 'Hover Text Color',
        labelCs: 'Text pri navrhu',
        type: 'color',
        default: '#ffffff',
        group: 'interaction',
      },
      {
        key: 'fullWidth',
        label: 'Full Width',
        labelCs: 'Plna sirka',
        type: 'boolean',
        default: false,
        group: 'layout',
      },
      {
        key: 'textTransform',
        label: 'Transform',
        labelCs: 'Transformace',
        type: 'select',
        default: 'none',
        options: [
          { value: 'none', label: 'None', labelCs: 'Zadna' },
          { value: 'uppercase', label: 'Uppercase', labelCs: 'Velka pismena' },
        ],
        group: 'typography',
      },
      {
        key: 'textAlignment',
        label: 'Alignment',
        labelCs: 'Zarovnani',
        type: 'select',
        default: 'center',
        options: [
          { value: 'left', label: 'Left', labelCs: 'Vlevo' },
          { value: 'center', label: 'Center', labelCs: 'Na stred' },
          { value: 'right', label: 'Right', labelCs: 'Vpravo' },
        ],
        group: 'layout',
      },
    ],
  },

  // -------------------------------------------------------------------------
  // Badge
  // -------------------------------------------------------------------------
  {
    id: 'badge',
    name: 'Badge',
    nameCs: 'Stitek',
    category: 'content',
    step: null,
    icon: 'Tag',
    locked: false,
    canReposition: true,
    canRestyle: true,
    description: 'Small badge or tag label.',
    descriptionCs: 'Maly stitek nebo oznaceni.',
    defaultProps: {
      text: 'New',
      textCs: 'Novinka',
      backgroundColor: '#ecfdf5',
      textColor: '#059669',
      fontSize: 12,
      fontWeight: '600',
      fontFamily: 'inherit',
      borderRadius: 20,
      borderColor: 'transparent',
      borderWidth: 0,
      padding: { top: 4, right: 12, bottom: 4, left: 12 },
      margin: { top: 0, right: 0, bottom: 8, left: 0 },
      textAlignment: 'center',
      textTransform: 'none',
      opacity: 1,
      display: 'inline-block',
    },
    editableProperties: [
      {
        key: 'text',
        label: 'Text',
        labelCs: 'Text',
        type: 'text',
        default: 'New',
        group: 'content',
      },
      {
        key: 'backgroundColor',
        label: 'Background',
        labelCs: 'Pozadi',
        type: 'color',
        default: '#ecfdf5',
        group: 'container',
      },
      {
        key: 'textColor',
        label: 'Text Color',
        labelCs: 'Barva textu',
        type: 'color',
        default: '#059669',
        group: 'typography',
      },
      {
        key: 'fontSize',
        label: 'Font Size',
        labelCs: 'Velikost fontu',
        type: 'number',
        default: 12,
        min: 8,
        max: 20,
        unit: 'px',
        group: 'typography',
      },
      {
        key: 'fontWeight',
        label: 'Font Weight',
        labelCs: 'Tucnost',
        type: 'select',
        default: '600',
        options: [
          { value: '400', label: 'Normal', labelCs: 'Normalni' },
          { value: '500', label: 'Medium', labelCs: 'Stredni' },
          { value: '600', label: 'Semi-bold', labelCs: 'Polotucny' },
          { value: '700', label: 'Bold', labelCs: 'Tucny' },
        ],
        group: 'typography',
      },
      {
        key: 'borderRadius',
        label: 'Corner Radius',
        labelCs: 'Zaobleni rohu',
        type: 'number',
        default: 20,
        min: 0,
        max: 50,
        unit: 'px',
        group: 'container',
      },
      {
        key: 'borderColor',
        label: 'Border Color',
        labelCs: 'Barva ramecku',
        type: 'color',
        default: 'transparent',
        group: 'container',
      },
      {
        key: 'borderWidth',
        label: 'Border Width',
        labelCs: 'Sirka ramecku',
        type: 'number',
        default: 0,
        min: 0,
        max: 4,
        unit: 'px',
        group: 'container',
      },
      {
        key: 'padding',
        label: 'Padding',
        labelCs: 'Vnitrni odsazeni',
        type: 'spacing',
        default: { top: 4, right: 12, bottom: 4, left: 12 },
        group: 'container',
      },
      {
        key: 'margin',
        label: 'Margin',
        labelCs: 'Vnejsi odsazeni',
        type: 'spacing',
        default: { top: 0, right: 0, bottom: 8, left: 0 },
        group: 'container',
      },
      {
        key: 'textTransform',
        label: 'Transform',
        labelCs: 'Transformace',
        type: 'select',
        default: 'none',
        options: [
          { value: 'none', label: 'None', labelCs: 'Zadna' },
          { value: 'uppercase', label: 'Uppercase', labelCs: 'Velka pismena' },
        ],
        group: 'typography',
      },
      {
        key: 'opacity',
        label: 'Opacity',
        labelCs: 'Pruhlednost',
        type: 'number',
        default: 1,
        min: 0,
        max: 1,
        step: 0.05,
        group: 'container',
      },
    ],
  },

  // -------------------------------------------------------------------------
  // Icon
  // -------------------------------------------------------------------------
  {
    id: 'icon',
    name: 'Icon',
    nameCs: 'Ikona',
    category: 'content',
    step: null,
    icon: 'Sparkle',
    locked: false,
    canReposition: true,
    canRestyle: true,
    description: 'Lucide icon with configurable size and color.',
    descriptionCs: 'Ikona z Lucide s nastavitelnou velikosti a barvou.',
    defaultProps: {
      iconName: 'Star',
      size: 24,
      color: '#6b7280',
      strokeWidth: 2,
      alignment: 'center',
      backgroundColor: 'transparent',
      borderRadius: 0,
      padding: { top: 0, right: 0, bottom: 0, left: 0 },
      margin: { top: 0, right: 0, bottom: 8, left: 0 },
      opacity: 1,
    },
    editableProperties: [
      {
        key: 'iconName',
        label: 'Icon Name',
        labelCs: 'Nazev ikony',
        type: 'text',
        default: 'Star',
        group: 'content',
      },
      {
        key: 'size',
        label: 'Size',
        labelCs: 'Velikost',
        type: 'number',
        default: 24,
        min: 12,
        max: 96,
        unit: 'px',
        group: 'dimensions',
      },
      {
        key: 'color',
        label: 'Color',
        labelCs: 'Barva',
        type: 'color',
        default: '#6b7280',
        group: 'icon',
      },
      {
        key: 'strokeWidth',
        label: 'Stroke Width',
        labelCs: 'Sirka cary',
        type: 'number',
        default: 2,
        min: 0.5,
        max: 4,
        step: 0.5,
        group: 'icon',
      },
      {
        key: 'alignment',
        label: 'Alignment',
        labelCs: 'Zarovnani',
        type: 'select',
        default: 'center',
        options: [
          { value: 'left', label: 'Left', labelCs: 'Vlevo' },
          { value: 'center', label: 'Center', labelCs: 'Na stred' },
          { value: 'right', label: 'Right', labelCs: 'Vpravo' },
        ],
        group: 'layout',
      },
      {
        key: 'backgroundColor',
        label: 'Background',
        labelCs: 'Pozadi',
        type: 'color',
        default: 'transparent',
        group: 'container',
      },
      {
        key: 'borderRadius',
        label: 'Corner Radius',
        labelCs: 'Zaobleni rohu',
        type: 'number',
        default: 0,
        min: 0,
        max: 50,
        unit: 'px',
        group: 'container',
      },
      {
        key: 'padding',
        label: 'Padding',
        labelCs: 'Vnitrni odsazeni',
        type: 'spacing',
        default: { top: 0, right: 0, bottom: 0, left: 0 },
        group: 'container',
      },
      {
        key: 'margin',
        label: 'Margin',
        labelCs: 'Vnejsi odsazeni',
        type: 'spacing',
        default: { top: 0, right: 0, bottom: 8, left: 0 },
        group: 'container',
      },
      {
        key: 'opacity',
        label: 'Opacity',
        labelCs: 'Pruhlednost',
        type: 'number',
        default: 1,
        min: 0,
        max: 1,
        step: 0.05,
        group: 'container',
      },
    ],
  },

  // -------------------------------------------------------------------------
  // Alert
  // -------------------------------------------------------------------------
  {
    id: 'alert',
    name: 'Alert',
    nameCs: 'Upozorneni',
    category: 'content',
    step: null,
    icon: 'AlertCircle',
    locked: false,
    canReposition: true,
    canRestyle: true,
    description: 'Alert box with info, warning, success, or error variant.',
    descriptionCs: 'Upozornovaci box s variantou info, varovani, uspech nebo chyba.',
    defaultProps: {
      variant: 'info',
      title: 'Information',
      titleCs: 'Informace',
      text: 'Alert message text here.',
      textCs: 'Text upozorneni zde.',
      backgroundColor: '#eff6ff',
      borderColor: '#93c5fd',
      borderWidth: 1,
      borderStyle: 'solid',
      borderRadius: 8,
      padding: { top: 16, right: 16, bottom: 16, left: 16 },
      margin: { top: 0, right: 0, bottom: 12, left: 0 },
      iconColor: '#3b82f6',
      iconSize: 20,
      titleColor: '#1e40af',
      titleFontSize: 14,
      titleFontWeight: '600',
      textColor: '#1d4ed8',
      textFontSize: 13,
      showIcon: true,
      showTitle: true,
      showDismiss: false,
      opacity: 1,
    },
    editableProperties: [
      {
        key: 'variant',
        label: 'Variant',
        labelCs: 'Varianta',
        type: 'select',
        default: 'info',
        options: [
          { value: 'info', label: 'Info', labelCs: 'Informace' },
          { value: 'warning', label: 'Warning', labelCs: 'Varovani' },
          { value: 'success', label: 'Success', labelCs: 'Uspech' },
          { value: 'error', label: 'Error', labelCs: 'Chyba' },
        ],
        group: 'content',
      },
      {
        key: 'title',
        label: 'Title',
        labelCs: 'Nadpis',
        type: 'text',
        default: 'Information',
        group: 'content',
      },
      {
        key: 'text',
        label: 'Message',
        labelCs: 'Zprava',
        type: 'text',
        default: 'Alert message text here.',
        group: 'content',
      },
      {
        key: 'backgroundColor',
        label: 'Background',
        labelCs: 'Pozadi',
        type: 'color',
        default: '#eff6ff',
        group: 'container',
      },
      {
        key: 'borderColor',
        label: 'Border Color',
        labelCs: 'Barva ramecku',
        type: 'color',
        default: '#93c5fd',
        group: 'container',
      },
      {
        key: 'borderWidth',
        label: 'Border Width',
        labelCs: 'Sirka ramecku',
        type: 'number',
        default: 1,
        min: 0,
        max: 4,
        unit: 'px',
        group: 'container',
      },
      {
        key: 'borderRadius',
        label: 'Corner Radius',
        labelCs: 'Zaobleni rohu',
        type: 'number',
        default: 8,
        min: 0,
        max: 24,
        unit: 'px',
        group: 'container',
      },
      {
        key: 'padding',
        label: 'Padding',
        labelCs: 'Vnitrni odsazeni',
        type: 'spacing',
        default: { top: 16, right: 16, bottom: 16, left: 16 },
        group: 'container',
      },
      {
        key: 'margin',
        label: 'Margin',
        labelCs: 'Vnejsi odsazeni',
        type: 'spacing',
        default: { top: 0, right: 0, bottom: 12, left: 0 },
        group: 'container',
      },
      {
        key: 'iconColor',
        label: 'Icon Color',
        labelCs: 'Barva ikony',
        type: 'color',
        default: '#3b82f6',
        group: 'icon',
      },
      {
        key: 'titleColor',
        label: 'Title Color',
        labelCs: 'Barva nadpisu',
        type: 'color',
        default: '#1e40af',
        group: 'typography',
      },
      {
        key: 'titleFontSize',
        label: 'Title Size',
        labelCs: 'Velikost nadpisu',
        type: 'number',
        default: 14,
        min: 10,
        max: 24,
        unit: 'px',
        group: 'typography',
      },
      {
        key: 'textColor',
        label: 'Text Color',
        labelCs: 'Barva textu',
        type: 'color',
        default: '#1d4ed8',
        group: 'typography',
      },
      {
        key: 'textFontSize',
        label: 'Text Size',
        labelCs: 'Velikost textu',
        type: 'number',
        default: 13,
        min: 10,
        max: 20,
        unit: 'px',
        group: 'typography',
      },
      {
        key: 'showIcon',
        label: 'Show Icon',
        labelCs: 'Zobrazit ikonu',
        type: 'boolean',
        default: true,
        group: 'content',
      },
      {
        key: 'showTitle',
        label: 'Show Title',
        labelCs: 'Zobrazit nadpis',
        type: 'boolean',
        default: true,
        group: 'content',
      },
      {
        key: 'showDismiss',
        label: 'Show Dismiss',
        labelCs: 'Zobrazit zavreni',
        type: 'boolean',
        default: false,
        group: 'content',
      },
      {
        key: 'opacity',
        label: 'Opacity',
        labelCs: 'Pruhlednost',
        type: 'number',
        default: 1,
        min: 0,
        max: 1,
        step: 0.05,
        group: 'container',
      },
    ],
  },

  // -------------------------------------------------------------------------
  // List
  // -------------------------------------------------------------------------
  {
    id: 'list',
    name: 'List',
    nameCs: 'Seznam',
    category: 'content',
    step: null,
    icon: 'List',
    locked: false,
    canReposition: true,
    canRestyle: true,
    description: 'Bulleted or numbered list.',
    descriptionCs: 'Odrazkovy nebo cislovany seznam.',
    defaultProps: {
      items: ['First item', 'Second item', 'Third item'],
      itemsCs: ['Prvni polozka', 'Druha polozka', 'Treti polozka'],
      listStyle: 'disc',
      color: '#374151',
      fontSize: 14,
      fontWeight: '400',
      fontFamily: 'inherit',
      lineHeight: 1.8,
      markerColor: '#6b7280',
      markerSize: 14,
      itemGap: 4,
      padding: { top: 0, right: 0, bottom: 0, left: 20 },
      margin: { top: 0, right: 0, bottom: 12, left: 0 },
      backgroundColor: 'transparent',
      borderRadius: 0,
      opacity: 1,
    },
    editableProperties: [
      {
        key: 'listStyle',
        label: 'List Style',
        labelCs: 'Styl seznamu',
        type: 'select',
        default: 'disc',
        options: [
          { value: 'disc', label: 'Bullet', labelCs: 'Odrazky' },
          { value: 'decimal', label: 'Numbered', labelCs: 'Cislovany' },
          { value: 'none', label: 'None', labelCs: 'Zadny' },
          { value: 'circle', label: 'Circle', labelCs: 'Kolecko' },
          { value: 'square', label: 'Square', labelCs: 'Ctverec' },
        ],
        group: 'content',
      },
      {
        key: 'color',
        label: 'Text Color',
        labelCs: 'Barva textu',
        type: 'color',
        default: '#374151',
        group: 'typography',
      },
      {
        key: 'fontSize',
        label: 'Font Size',
        labelCs: 'Velikost fontu',
        type: 'number',
        default: 14,
        min: 10,
        max: 24,
        unit: 'px',
        group: 'typography',
      },
      {
        key: 'fontWeight',
        label: 'Font Weight',
        labelCs: 'Tucnost',
        type: 'select',
        default: '400',
        options: [
          { value: '400', label: 'Normal', labelCs: 'Normalni' },
          { value: '500', label: 'Medium', labelCs: 'Stredni' },
          { value: '600', label: 'Semi-bold', labelCs: 'Polotucny' },
          { value: '700', label: 'Bold', labelCs: 'Tucny' },
        ],
        group: 'typography',
      },
      {
        key: 'lineHeight',
        label: 'Line Height',
        labelCs: 'Vyska radku',
        type: 'number',
        default: 1.8,
        min: 1,
        max: 3,
        step: 0.1,
        group: 'typography',
      },
      {
        key: 'markerColor',
        label: 'Marker Color',
        labelCs: 'Barva odrazky',
        type: 'color',
        default: '#6b7280',
        group: 'typography',
      },
      {
        key: 'itemGap',
        label: 'Item Gap',
        labelCs: 'Mezera mezi polozkami',
        type: 'number',
        default: 4,
        min: 0,
        max: 24,
        unit: 'px',
        group: 'layout',
      },
      {
        key: 'padding',
        label: 'Padding',
        labelCs: 'Vnitrni odsazeni',
        type: 'spacing',
        default: { top: 0, right: 0, bottom: 0, left: 20 },
        group: 'container',
      },
      {
        key: 'margin',
        label: 'Margin',
        labelCs: 'Vnejsi odsazeni',
        type: 'spacing',
        default: { top: 0, right: 0, bottom: 12, left: 0 },
        group: 'container',
      },
      {
        key: 'backgroundColor',
        label: 'Background',
        labelCs: 'Pozadi',
        type: 'color',
        default: 'transparent',
        group: 'container',
      },
      {
        key: 'borderRadius',
        label: 'Corner Radius',
        labelCs: 'Zaobleni rohu',
        type: 'number',
        default: 0,
        min: 0,
        max: 16,
        unit: 'px',
        group: 'container',
      },
      {
        key: 'opacity',
        label: 'Opacity',
        labelCs: 'Pruhlednost',
        type: 'number',
        default: 1,
        min: 0,
        max: 1,
        step: 0.05,
        group: 'container',
      },
    ],
  },
];
