/**
 * formBlocks.js -- Form element block definitions for the Widget Builder.
 *
 * Form blocks represent individual form inputs that can be placed
 * within the widget layout. They are typically used in custom step
 * layouts or as additions alongside the calculator blocks.
 */

/** Shared form-field base properties used by all input blocks. */
const FORM_BASE_PROPS = [
  {
    key: 'labelText',
    label: 'Label',
    labelCs: 'Popisek',
    type: 'text',
    default: 'Label',
    group: 'content',
  },
  {
    key: 'labelColor',
    label: 'Label Color',
    labelCs: 'Barva popisku',
    type: 'color',
    default: '#374151',
    group: 'typography',
  },
  {
    key: 'labelFontSize',
    label: 'Label Size',
    labelCs: 'Velikost popisku',
    type: 'number',
    default: 14,
    min: 10,
    max: 20,
    unit: 'px',
    group: 'typography',
  },
  {
    key: 'labelFontWeight',
    label: 'Label Weight',
    labelCs: 'Tucnost popisku',
    type: 'select',
    default: '500',
    options: [
      { value: '400', label: 'Normal', labelCs: 'Normalni' },
      { value: '500', label: 'Medium', labelCs: 'Stredni' },
      { value: '600', label: 'Semi-bold', labelCs: 'Polotucny' },
    ],
    group: 'typography',
  },
  {
    key: 'showLabel',
    label: 'Show Label',
    labelCs: 'Zobrazit popisek',
    type: 'boolean',
    default: true,
    group: 'content',
  },
  {
    key: 'required',
    label: 'Required',
    labelCs: 'Povinne',
    type: 'boolean',
    default: false,
    group: 'validation',
  },
  {
    key: 'helperText',
    label: 'Helper Text',
    labelCs: 'Napoveda',
    type: 'text',
    default: '',
    group: 'content',
  },
  {
    key: 'helperTextColor',
    label: 'Helper Color',
    labelCs: 'Barva napovedy',
    type: 'color',
    default: '#9ca3af',
    group: 'typography',
  },
  {
    key: 'errorColor',
    label: 'Error Color',
    labelCs: 'Barva chyby',
    type: 'color',
    default: '#ef4444',
    group: 'validation',
  },
  {
    key: 'margin',
    label: 'Margin',
    labelCs: 'Vnejsi odsazeni',
    type: 'spacing',
    default: { top: 0, right: 0, bottom: 12, left: 0 },
    group: 'container',
  },
  {
    key: 'opacity',
    label: 'Opacity',
    labelCs: 'Pruhlednost',
    type: 'number',
    default: 1,
    min: 0,
    max: 1,
    step: 0.05,
    group: 'container',
  },
];

/** Shared text-input style properties (used by text input, textarea, number). */
const INPUT_STYLE_PROPS = [
  {
    key: 'inputBackgroundColor',
    label: 'Input Background',
    labelCs: 'Pozadi inputu',
    type: 'color',
    default: '#ffffff',
    group: 'form',
  },
  {
    key: 'inputBorderColor',
    label: 'Input Border',
    labelCs: 'Ramecek inputu',
    type: 'color',
    default: '#d1d5db',
    group: 'form',
  },
  {
    key: 'inputBorderWidth',
    label: 'Border Width',
    labelCs: 'Sirka ramecku',
    type: 'number',
    default: 1,
    min: 0,
    max: 4,
    unit: 'px',
    group: 'form',
  },
  {
    key: 'inputBorderRadius',
    label: 'Input Radius',
    labelCs: 'Zaobleni inputu',
    type: 'number',
    default: 6,
    min: 0,
    max: 24,
    unit: 'px',
    group: 'form',
  },
  {
    key: 'inputFocusBorderColor',
    label: 'Focus Border',
    labelCs: 'Ramecek pri fokusu',
    type: 'color',
    default: '#3b82f6',
    group: 'form',
  },
  {
    key: 'inputFontSize',
    label: 'Input Font Size',
    labelCs: 'Velikost textu',
    type: 'number',
    default: 14,
    min: 12,
    max: 20,
    unit: 'px',
    group: 'form',
  },
  {
    key: 'inputTextColor',
    label: 'Input Text Color',
    labelCs: 'Barva textu inputu',
    type: 'color',
    default: '#111827',
    group: 'form',
  },
  {
    key: 'placeholderColor',
    label: 'Placeholder Color',
    labelCs: 'Barva zastupneho textu',
    type: 'color',
    default: '#9ca3af',
    group: 'form',
  },
  {
    key: 'inputPadding',
    label: 'Input Padding',
    labelCs: 'Odsazeni inputu',
    type: 'spacing',
    default: { top: 10, right: 12, bottom: 10, left: 12 },
    group: 'form',
  },
];

export const formBlocks = [
  // -------------------------------------------------------------------------
  // TextInput
  // -------------------------------------------------------------------------
  {
    id: 'text-input',
    name: 'Text Input',
    nameCs: 'Textovy vstup',
    category: 'form',
    step: null,
    icon: 'TextCursorInput',
    locked: false,
    canReposition: true,
    canRestyle: true,
    description: 'Single-line text input with label.',
    descriptionCs: 'Jednoradkovy textovy vstup s popiskem.',
    defaultProps: {
      labelText: 'Name',
      labelTextCs: 'Jmeno',
      placeholder: 'Enter text...',
      placeholderCs: 'Zadejte text...',
      inputType: 'text',
      labelColor: '#374151',
      labelFontSize: 14,
      labelFontWeight: '500',
      showLabel: true,
      required: false,
      helperText: '',
      helperTextColor: '#9ca3af',
      errorColor: '#ef4444',
      inputBackgroundColor: '#ffffff',
      inputBorderColor: '#d1d5db',
      inputBorderWidth: 1,
      inputBorderRadius: 6,
      inputFocusBorderColor: '#3b82f6',
      inputFontSize: 14,
      inputTextColor: '#111827',
      placeholderColor: '#9ca3af',
      inputPadding: { top: 10, right: 12, bottom: 10, left: 12 },
      margin: { top: 0, right: 0, bottom: 12, left: 0 },
      opacity: 1,
      fullWidth: true,
      maxLength: 0,
    },
    editableProperties: [
      ...FORM_BASE_PROPS,
      ...INPUT_STYLE_PROPS,
      {
        key: 'placeholder',
        label: 'Placeholder',
        labelCs: 'Zastupny text',
        type: 'text',
        default: 'Enter text...',
        group: 'content',
      },
      {
        key: 'inputType',
        label: 'Input Type',
        labelCs: 'Typ inputu',
        type: 'select',
        default: 'text',
        options: [
          { value: 'text', label: 'Text', labelCs: 'Text' },
          { value: 'email', label: 'Email', labelCs: 'Email' },
          { value: 'tel', label: 'Phone', labelCs: 'Telefon' },
          { value: 'url', label: 'URL', labelCs: 'URL' },
          { value: 'password', label: 'Password', labelCs: 'Heslo' },
        ],
        group: 'content',
      },
      {
        key: 'fullWidth',
        label: 'Full Width',
        labelCs: 'Plna sirka',
        type: 'boolean',
        default: true,
        group: 'layout',
      },
      {
        key: 'maxLength',
        label: 'Max Length',
        labelCs: 'Max delka',
        type: 'number',
        default: 0,
        min: 0,
        max: 1000,
        group: 'validation',
      },
    ],
  },

  // -------------------------------------------------------------------------
  // SelectInput
  // -------------------------------------------------------------------------
  {
    id: 'select-input',
    name: 'Select Input',
    nameCs: 'Vyber ze seznamu',
    category: 'form',
    step: null,
    icon: 'ChevronDown',
    locked: false,
    canReposition: true,
    canRestyle: true,
    description: 'Dropdown select field with label.',
    descriptionCs: 'Rozbalovaci vyber s popiskem.',
    defaultProps: {
      labelText: 'Select option',
      labelTextCs: 'Vyberte moznost',
      placeholder: 'Choose...',
      placeholderCs: 'Vyberte...',
      options: [
        { value: 'option1', label: 'Option 1', labelCs: 'Moznost 1' },
        { value: 'option2', label: 'Option 2', labelCs: 'Moznost 2' },
        { value: 'option3', label: 'Option 3', labelCs: 'Moznost 3' },
      ],
      labelColor: '#374151',
      labelFontSize: 14,
      labelFontWeight: '500',
      showLabel: true,
      required: false,
      helperText: '',
      helperTextColor: '#9ca3af',
      errorColor: '#ef4444',
      inputBackgroundColor: '#ffffff',
      inputBorderColor: '#d1d5db',
      inputBorderWidth: 1,
      inputBorderRadius: 6,
      inputFocusBorderColor: '#3b82f6',
      inputFontSize: 14,
      inputTextColor: '#111827',
      placeholderColor: '#9ca3af',
      inputPadding: { top: 10, right: 12, bottom: 10, left: 12 },
      margin: { top: 0, right: 0, bottom: 12, left: 0 },
      opacity: 1,
      fullWidth: true,
      chevronColor: '#6b7280',
    },
    editableProperties: [
      ...FORM_BASE_PROPS,
      ...INPUT_STYLE_PROPS,
      {
        key: 'placeholder',
        label: 'Placeholder',
        labelCs: 'Zastupny text',
        type: 'text',
        default: 'Choose...',
        group: 'content',
      },
      {
        key: 'fullWidth',
        label: 'Full Width',
        labelCs: 'Plna sirka',
        type: 'boolean',
        default: true,
        group: 'layout',
      },
      {
        key: 'chevronColor',
        label: 'Chevron Color',
        labelCs: 'Barva sipky',
        type: 'color',
        default: '#6b7280',
        group: 'icon',
      },
    ],
  },

  // -------------------------------------------------------------------------
  // CheckboxInput
  // -------------------------------------------------------------------------
  {
    id: 'checkbox-input',
    name: 'Checkbox',
    nameCs: 'Zaskrtavaci pole',
    category: 'form',
    step: null,
    icon: 'CheckSquare',
    locked: false,
    canReposition: true,
    canRestyle: true,
    description: 'Checkbox with label text.',
    descriptionCs: 'Zaskrtavaci pole s textem popisku.',
    defaultProps: {
      labelText: 'I agree to the terms',
      labelTextCs: 'Souhlasim s podminkami',
      labelColor: '#374151',
      labelFontSize: 14,
      labelFontWeight: '400',
      showLabel: true,
      required: false,
      helperText: '',
      helperTextColor: '#9ca3af',
      errorColor: '#ef4444',
      checkboxSize: 18,
      checkboxBorderColor: '#d1d5db',
      checkboxBorderRadius: 4,
      checkboxCheckedColor: '#3b82f6',
      checkboxCheckedBorderColor: '#3b82f6',
      checkmarkColor: '#ffffff',
      gap: 8,
      margin: { top: 0, right: 0, bottom: 12, left: 0 },
      opacity: 1,
      defaultChecked: false,
    },
    editableProperties: [
      ...FORM_BASE_PROPS,
      {
        key: 'checkboxSize',
        label: 'Checkbox Size',
        labelCs: 'Velikost checkboxu',
        type: 'number',
        default: 18,
        min: 14,
        max: 28,
        unit: 'px',
        group: 'form',
      },
      {
        key: 'checkboxBorderColor',
        label: 'Border Color',
        labelCs: 'Barva ramecku',
        type: 'color',
        default: '#d1d5db',
        group: 'form',
      },
      {
        key: 'checkboxBorderRadius',
        label: 'Border Radius',
        labelCs: 'Zaobleni',
        type: 'number',
        default: 4,
        min: 0,
        max: 14,
        unit: 'px',
        group: 'form',
      },
      {
        key: 'checkboxCheckedColor',
        label: 'Checked Color',
        labelCs: 'Barva pri zaskrtnuti',
        type: 'color',
        default: '#3b82f6',
        group: 'form',
      },
      {
        key: 'checkboxCheckedBorderColor',
        label: 'Checked Border',
        labelCs: 'Ramecek pri zaskrtnuti',
        type: 'color',
        default: '#3b82f6',
        group: 'form',
      },
      {
        key: 'checkmarkColor',
        label: 'Checkmark Color',
        labelCs: 'Barva zatrzitka',
        type: 'color',
        default: '#ffffff',
        group: 'form',
      },
      {
        key: 'gap',
        label: 'Gap',
        labelCs: 'Mezera',
        type: 'number',
        default: 8,
        min: 4,
        max: 20,
        unit: 'px',
        group: 'layout',
      },
      {
        key: 'defaultChecked',
        label: 'Default Checked',
        labelCs: 'Vychozi zaskrtnute',
        type: 'boolean',
        default: false,
        group: 'content',
      },
    ],
  },

  // -------------------------------------------------------------------------
  // RadioGroup
  // -------------------------------------------------------------------------
  {
    id: 'radio-group',
    name: 'Radio Group',
    nameCs: 'Skupina radio',
    category: 'form',
    step: null,
    icon: 'Circle',
    locked: false,
    canReposition: true,
    canRestyle: true,
    description: 'Radio button group with multiple options.',
    descriptionCs: 'Skupina radio tlacitek s vice moznostmi.',
    defaultProps: {
      labelText: 'Choose one',
      labelTextCs: 'Vyberte jednu moznost',
      options: [
        { value: 'option1', label: 'Option 1', labelCs: 'Moznost 1' },
        { value: 'option2', label: 'Option 2', labelCs: 'Moznost 2' },
        { value: 'option3', label: 'Option 3', labelCs: 'Moznost 3' },
      ],
      labelColor: '#374151',
      labelFontSize: 14,
      labelFontWeight: '500',
      showLabel: true,
      required: false,
      helperText: '',
      helperTextColor: '#9ca3af',
      errorColor: '#ef4444',
      radioSize: 18,
      radioBorderColor: '#d1d5db',
      radioSelectedColor: '#3b82f6',
      radioSelectedBorderColor: '#3b82f6',
      radioDotColor: '#ffffff',
      optionLabelColor: '#374151',
      optionLabelFontSize: 14,
      optionGap: 8,
      direction: 'vertical',
      gap: 8,
      margin: { top: 0, right: 0, bottom: 12, left: 0 },
      opacity: 1,
    },
    editableProperties: [
      ...FORM_BASE_PROPS,
      {
        key: 'radioSize',
        label: 'Radio Size',
        labelCs: 'Velikost radio',
        type: 'number',
        default: 18,
        min: 14,
        max: 28,
        unit: 'px',
        group: 'form',
      },
      {
        key: 'radioBorderColor',
        label: 'Border Color',
        labelCs: 'Barva ramecku',
        type: 'color',
        default: '#d1d5db',
        group: 'form',
      },
      {
        key: 'radioSelectedColor',
        label: 'Selected Color',
        labelCs: 'Barva vybrane',
        type: 'color',
        default: '#3b82f6',
        group: 'form',
      },
      {
        key: 'radioSelectedBorderColor',
        label: 'Selected Border',
        labelCs: 'Ramecek vybrane',
        type: 'color',
        default: '#3b82f6',
        group: 'form',
      },
      {
        key: 'radioDotColor',
        label: 'Dot Color',
        labelCs: 'Barva tecky',
        type: 'color',
        default: '#ffffff',
        group: 'form',
      },
      {
        key: 'optionLabelColor',
        label: 'Option Label Color',
        labelCs: 'Barva popisku moznosti',
        type: 'color',
        default: '#374151',
        group: 'typography',
      },
      {
        key: 'optionLabelFontSize',
        label: 'Option Label Size',
        labelCs: 'Velikost popisku moznosti',
        type: 'number',
        default: 14,
        min: 10,
        max: 20,
        unit: 'px',
        group: 'typography',
      },
      {
        key: 'direction',
        label: 'Direction',
        labelCs: 'Smer',
        type: 'select',
        default: 'vertical',
        options: [
          { value: 'vertical', label: 'Vertical', labelCs: 'Vertikalni' },
          { value: 'horizontal', label: 'Horizontal', labelCs: 'Horizontalni' },
        ],
        group: 'layout',
      },
      {
        key: 'gap',
        label: 'Option Gap',
        labelCs: 'Mezera mezi moznostmi',
        type: 'number',
        default: 8,
        min: 4,
        max: 24,
        unit: 'px',
        group: 'layout',
      },
    ],
  },

  // -------------------------------------------------------------------------
  // TextArea
  // -------------------------------------------------------------------------
  {
    id: 'textarea',
    name: 'Text Area',
    nameCs: 'Textova oblast',
    category: 'form',
    step: null,
    icon: 'AlignLeft',
    locked: false,
    canReposition: true,
    canRestyle: true,
    description: 'Multi-line text input field.',
    descriptionCs: 'Viceriadkove textove vstupni pole.',
    defaultProps: {
      labelText: 'Notes',
      labelTextCs: 'Poznamky',
      placeholder: 'Enter your text...',
      placeholderCs: 'Zadejte vas text...',
      labelColor: '#374151',
      labelFontSize: 14,
      labelFontWeight: '500',
      showLabel: true,
      required: false,
      helperText: '',
      helperTextColor: '#9ca3af',
      errorColor: '#ef4444',
      inputBackgroundColor: '#ffffff',
      inputBorderColor: '#d1d5db',
      inputBorderWidth: 1,
      inputBorderRadius: 6,
      inputFocusBorderColor: '#3b82f6',
      inputFontSize: 14,
      inputTextColor: '#111827',
      placeholderColor: '#9ca3af',
      inputPadding: { top: 10, right: 12, bottom: 10, left: 12 },
      margin: { top: 0, right: 0, bottom: 12, left: 0 },
      opacity: 1,
      fullWidth: true,
      rows: 4,
      minRows: 2,
      maxRows: 10,
      resize: 'vertical',
      maxLength: 0,
    },
    editableProperties: [
      ...FORM_BASE_PROPS,
      ...INPUT_STYLE_PROPS,
      {
        key: 'placeholder',
        label: 'Placeholder',
        labelCs: 'Zastupny text',
        type: 'text',
        default: 'Enter your text...',
        group: 'content',
      },
      {
        key: 'rows',
        label: 'Rows',
        labelCs: 'Radky',
        type: 'number',
        default: 4,
        min: 1,
        max: 20,
        group: 'dimensions',
      },
      {
        key: 'resize',
        label: 'Resize',
        labelCs: 'Zmena velikosti',
        type: 'select',
        default: 'vertical',
        options: [
          { value: 'none', label: 'None', labelCs: 'Zadna' },
          { value: 'vertical', label: 'Vertical', labelCs: 'Vertikalni' },
          { value: 'horizontal', label: 'Horizontal', labelCs: 'Horizontalni' },
          { value: 'both', label: 'Both', labelCs: 'Oboji' },
        ],
        group: 'dimensions',
      },
      {
        key: 'fullWidth',
        label: 'Full Width',
        labelCs: 'Plna sirka',
        type: 'boolean',
        default: true,
        group: 'layout',
      },
      {
        key: 'maxLength',
        label: 'Max Length',
        labelCs: 'Max delka',
        type: 'number',
        default: 0,
        min: 0,
        max: 5000,
        group: 'validation',
      },
    ],
  },

  // -------------------------------------------------------------------------
  // NumberInput
  // -------------------------------------------------------------------------
  {
    id: 'number-input',
    name: 'Number Input',
    nameCs: 'Ciselny vstup',
    category: 'form',
    step: null,
    icon: 'Hash',
    locked: false,
    canReposition: true,
    canRestyle: true,
    description: 'Number input with increment/decrement buttons.',
    descriptionCs: 'Ciselny vstup s tlacitky plus a minus.',
    defaultProps: {
      labelText: 'Quantity',
      labelTextCs: 'Mnozstvi',
      placeholder: '0',
      labelColor: '#374151',
      labelFontSize: 14,
      labelFontWeight: '500',
      showLabel: true,
      required: false,
      helperText: '',
      helperTextColor: '#9ca3af',
      errorColor: '#ef4444',
      inputBackgroundColor: '#ffffff',
      inputBorderColor: '#d1d5db',
      inputBorderWidth: 1,
      inputBorderRadius: 6,
      inputFocusBorderColor: '#3b82f6',
      inputFontSize: 14,
      inputTextColor: '#111827',
      placeholderColor: '#9ca3af',
      inputPadding: { top: 10, right: 12, bottom: 10, left: 12 },
      margin: { top: 0, right: 0, bottom: 12, left: 0 },
      opacity: 1,
      min: 0,
      max: 9999,
      stepValue: 1,
      showButtons: true,
      buttonColor: '#3b82f6',
      buttonTextColor: '#ffffff',
      buttonBorderRadius: 6,
      buttonSize: 32,
      fullWidth: true,
      unit: '',
      unitColor: '#6b7280',
      unitPosition: 'right',
    },
    editableProperties: [
      ...FORM_BASE_PROPS,
      ...INPUT_STYLE_PROPS,
      {
        key: 'placeholder',
        label: 'Placeholder',
        labelCs: 'Zastupny text',
        type: 'text',
        default: '0',
        group: 'content',
      },
      {
        key: 'min',
        label: 'Min Value',
        labelCs: 'Minimalni hodnota',
        type: 'number',
        default: 0,
        min: -99999,
        max: 99999,
        group: 'validation',
      },
      {
        key: 'max',
        label: 'Max Value',
        labelCs: 'Maximalni hodnota',
        type: 'number',
        default: 9999,
        min: -99999,
        max: 99999,
        group: 'validation',
      },
      {
        key: 'stepValue',
        label: 'Step',
        labelCs: 'Krok',
        type: 'number',
        default: 1,
        min: 0.01,
        max: 100,
        step: 0.01,
        group: 'validation',
      },
      {
        key: 'showButtons',
        label: 'Show +/- Buttons',
        labelCs: 'Zobrazit +/- tlacitka',
        type: 'boolean',
        default: true,
        group: 'content',
      },
      {
        key: 'buttonColor',
        label: 'Button Color',
        labelCs: 'Barva tlacitka',
        type: 'color',
        default: '#3b82f6',
        group: 'button',
      },
      {
        key: 'buttonTextColor',
        label: 'Button Text Color',
        labelCs: 'Barva textu tlacitka',
        type: 'color',
        default: '#ffffff',
        group: 'button',
      },
      {
        key: 'buttonBorderRadius',
        label: 'Button Radius',
        labelCs: 'Zaobleni tlacitka',
        type: 'number',
        default: 6,
        min: 0,
        max: 16,
        unit: 'px',
        group: 'button',
      },
      {
        key: 'buttonSize',
        label: 'Button Size',
        labelCs: 'Velikost tlacitka',
        type: 'number',
        default: 32,
        min: 24,
        max: 48,
        unit: 'px',
        group: 'button',
      },
      {
        key: 'fullWidth',
        label: 'Full Width',
        labelCs: 'Plna sirka',
        type: 'boolean',
        default: true,
        group: 'layout',
      },
      {
        key: 'unit',
        label: 'Unit',
        labelCs: 'Jednotka',
        type: 'text',
        default: '',
        group: 'content',
      },
      {
        key: 'unitColor',
        label: 'Unit Color',
        labelCs: 'Barva jednotky',
        type: 'color',
        default: '#6b7280',
        group: 'typography',
      },
      {
        key: 'unitPosition',
        label: 'Unit Position',
        labelCs: 'Pozice jednotky',
        type: 'select',
        default: 'right',
        options: [
          { value: 'left', label: 'Left', labelCs: 'Vlevo' },
          { value: 'right', label: 'Right', labelCs: 'Vpravo' },
        ],
        group: 'typography',
      },
    ],
  },
];
