/**
 * layoutBlocks.js -- Layout / structural block definitions for the Widget Builder.
 *
 * Layout blocks provide structural containers: sections, rows, columns,
 * spacers, dividers, and cards. They do not carry functional logic --
 * they are pure visual/structural wrappers used to arrange content.
 */

export const layoutBlocks = [
  // -------------------------------------------------------------------------
  // Section
  // -------------------------------------------------------------------------
  {
    id: 'section',
    name: 'Section',
    nameCs: 'Sekce',
    category: 'layout',
    step: null,
    icon: 'LayoutPanelTop',
    locked: false,
    canReposition: true,
    canRestyle: true,
    description: 'Full-width container section with background.',
    descriptionCs: 'Sekce pres celou sirku s pozadim.',
    defaultProps: {
      backgroundColor: '#ffffff',
      borderColor: '#e5e7eb',
      borderWidth: 0,
      borderStyle: 'none',
      borderRadius: 0,
      padding: { top: 24, right: 24, bottom: 24, left: 24 },
      margin: { top: 0, right: 0, bottom: 0, left: 0 },
      boxShadow: 'none',
      opacity: 1,
      minHeight: 0,
      maxWidth: 'none',
      overflow: 'visible',
      display: 'block',
      position: 'relative',
    },
    editableProperties: [
      {
        key: 'backgroundColor',
        label: 'Background',
        labelCs: 'Pozadi',
        type: 'color',
        default: '#ffffff',
        group: 'container',
      },
      {
        key: 'borderColor',
        label: 'Border Color',
        labelCs: 'Barva ramecku',
        type: 'color',
        default: '#e5e7eb',
        group: 'container',
      },
      {
        key: 'borderWidth',
        label: 'Border Width',
        labelCs: 'Sirka ramecku',
        type: 'number',
        default: 0,
        min: 0,
        max: 8,
        unit: 'px',
        group: 'container',
      },
      {
        key: 'borderStyle',
        label: 'Border Style',
        labelCs: 'Styl ramecku',
        type: 'select',
        default: 'none',
        options: [
          { value: 'none', label: 'None', labelCs: 'Zadny' },
          { value: 'solid', label: 'Solid', labelCs: 'Plny' },
          { value: 'dashed', label: 'Dashed', labelCs: 'Carkovany' },
          { value: 'dotted', label: 'Dotted', labelCs: 'Teckovany' },
        ],
        group: 'container',
      },
      {
        key: 'borderRadius',
        label: 'Corner Radius',
        labelCs: 'Zaobleni rohu',
        type: 'number',
        default: 0,
        min: 0,
        max: 32,
        unit: 'px',
        group: 'container',
      },
      {
        key: 'padding',
        label: 'Padding',
        labelCs: 'Vnitrni odsazeni',
        type: 'spacing',
        default: { top: 24, right: 24, bottom: 24, left: 24 },
        group: 'container',
      },
      {
        key: 'margin',
        label: 'Margin',
        labelCs: 'Vnejsi odsazeni',
        type: 'spacing',
        default: { top: 0, right: 0, bottom: 0, left: 0 },
        group: 'container',
      },
      {
        key: 'boxShadow',
        label: 'Shadow',
        labelCs: 'Stin',
        type: 'shadow',
        default: 'none',
        options: [
          { value: 'none', label: 'None', labelCs: 'Zadny' },
          { value: '0 1px 3px rgba(0,0,0,0.1)', label: 'Small', labelCs: 'Maly' },
          { value: '0 4px 12px rgba(0,0,0,0.1)', label: 'Medium', labelCs: 'Stredni' },
          { value: '0 8px 24px rgba(0,0,0,0.12)', label: 'Large', labelCs: 'Velky' },
        ],
        group: 'container',
      },
      {
        key: 'opacity',
        label: 'Opacity',
        labelCs: 'Pruhlednost',
        type: 'number',
        default: 1,
        min: 0,
        max: 1,
        step: 0.05,
        group: 'container',
      },
      {
        key: 'minHeight',
        label: 'Min Height',
        labelCs: 'Minimalni vyska',
        type: 'number',
        default: 0,
        min: 0,
        max: 800,
        unit: 'px',
        group: 'dimensions',
      },
      {
        key: 'maxWidth',
        label: 'Max Width',
        labelCs: 'Maximalni sirka',
        type: 'select',
        default: 'none',
        options: [
          { value: 'none', label: 'None', labelCs: 'Zadna' },
          { value: '480px', label: '480px', labelCs: '480px' },
          { value: '640px', label: '640px', labelCs: '640px' },
          { value: '800px', label: '800px', labelCs: '800px' },
          { value: '100%', label: '100%', labelCs: '100%' },
        ],
        group: 'dimensions',
      },
      {
        key: 'overflow',
        label: 'Overflow',
        labelCs: 'Preteceni',
        type: 'select',
        default: 'visible',
        options: [
          { value: 'visible', label: 'Visible', labelCs: 'Viditelne' },
          { value: 'hidden', label: 'Hidden', labelCs: 'Skryte' },
          { value: 'auto', label: 'Auto', labelCs: 'Automaticke' },
        ],
        group: 'dimensions',
      },
    ],
  },

  // -------------------------------------------------------------------------
  // Row
  // -------------------------------------------------------------------------
  {
    id: 'row',
    name: 'Row',
    nameCs: 'Radek',
    category: 'layout',
    step: null,
    icon: 'Columns',
    locked: false,
    canReposition: true,
    canRestyle: true,
    description: 'Horizontal flex row for side-by-side layout.',
    descriptionCs: 'Horizontalni flexbox radek pro rozlozeni vedle sebe.',
    defaultProps: {
      backgroundColor: 'transparent',
      borderColor: 'transparent',
      borderWidth: 0,
      borderStyle: 'none',
      borderRadius: 0,
      padding: { top: 0, right: 0, bottom: 0, left: 0 },
      margin: { top: 0, right: 0, bottom: 0, left: 0 },
      boxShadow: 'none',
      opacity: 1,
      gap: 16,
      justifyContent: 'flex-start',
      alignItems: 'stretch',
      flexWrap: 'wrap',
      minHeight: 0,
    },
    editableProperties: [
      {
        key: 'backgroundColor',
        label: 'Background',
        labelCs: 'Pozadi',
        type: 'color',
        default: 'transparent',
        group: 'container',
      },
      {
        key: 'borderColor',
        label: 'Border Color',
        labelCs: 'Barva ramecku',
        type: 'color',
        default: 'transparent',
        group: 'container',
      },
      {
        key: 'borderWidth',
        label: 'Border Width',
        labelCs: 'Sirka ramecku',
        type: 'number',
        default: 0,
        min: 0,
        max: 8,
        unit: 'px',
        group: 'container',
      },
      {
        key: 'borderRadius',
        label: 'Corner Radius',
        labelCs: 'Zaobleni rohu',
        type: 'number',
        default: 0,
        min: 0,
        max: 32,
        unit: 'px',
        group: 'container',
      },
      {
        key: 'padding',
        label: 'Padding',
        labelCs: 'Vnitrni odsazeni',
        type: 'spacing',
        default: { top: 0, right: 0, bottom: 0, left: 0 },
        group: 'container',
      },
      {
        key: 'margin',
        label: 'Margin',
        labelCs: 'Vnejsi odsazeni',
        type: 'spacing',
        default: { top: 0, right: 0, bottom: 0, left: 0 },
        group: 'container',
      },
      {
        key: 'boxShadow',
        label: 'Shadow',
        labelCs: 'Stin',
        type: 'shadow',
        default: 'none',
        options: [
          { value: 'none', label: 'None', labelCs: 'Zadny' },
          { value: '0 1px 3px rgba(0,0,0,0.1)', label: 'Small', labelCs: 'Maly' },
          { value: '0 4px 12px rgba(0,0,0,0.1)', label: 'Medium', labelCs: 'Stredni' },
        ],
        group: 'container',
      },
      {
        key: 'opacity',
        label: 'Opacity',
        labelCs: 'Pruhlednost',
        type: 'number',
        default: 1,
        min: 0,
        max: 1,
        step: 0.05,
        group: 'container',
      },
      {
        key: 'gap',
        label: 'Gap',
        labelCs: 'Mezera',
        type: 'number',
        default: 16,
        min: 0,
        max: 64,
        unit: 'px',
        group: 'layout',
      },
      {
        key: 'justifyContent',
        label: 'Justify',
        labelCs: 'Zarovnani hlavni osa',
        type: 'select',
        default: 'flex-start',
        options: [
          { value: 'flex-start', label: 'Start', labelCs: 'Zacatek' },
          { value: 'center', label: 'Center', labelCs: 'Stred' },
          { value: 'flex-end', label: 'End', labelCs: 'Konec' },
          { value: 'space-between', label: 'Space Between', labelCs: 'Mezera mezi' },
          { value: 'space-around', label: 'Space Around', labelCs: 'Mezera kolem' },
          { value: 'space-evenly', label: 'Space Evenly', labelCs: 'Rovnomerne' },
        ],
        group: 'layout',
      },
      {
        key: 'alignItems',
        label: 'Align Items',
        labelCs: 'Zarovnani vedlejsi osa',
        type: 'select',
        default: 'stretch',
        options: [
          { value: 'stretch', label: 'Stretch', labelCs: 'Roztahnout' },
          { value: 'flex-start', label: 'Start', labelCs: 'Zacatek' },
          { value: 'center', label: 'Center', labelCs: 'Stred' },
          { value: 'flex-end', label: 'End', labelCs: 'Konec' },
          { value: 'baseline', label: 'Baseline', labelCs: 'Zakladna' },
        ],
        group: 'layout',
      },
      {
        key: 'flexWrap',
        label: 'Wrap',
        labelCs: 'Zalamovani',
        type: 'select',
        default: 'wrap',
        options: [
          { value: 'nowrap', label: 'No Wrap', labelCs: 'Bez zalamovani' },
          { value: 'wrap', label: 'Wrap', labelCs: 'Zalamovat' },
          { value: 'wrap-reverse', label: 'Wrap Reverse', labelCs: 'Zalamovat opacne' },
        ],
        group: 'layout',
      },
      {
        key: 'minHeight',
        label: 'Min Height',
        labelCs: 'Minimalni vyska',
        type: 'number',
        default: 0,
        min: 0,
        max: 400,
        unit: 'px',
        group: 'dimensions',
      },
    ],
  },

  // -------------------------------------------------------------------------
  // Column
  // -------------------------------------------------------------------------
  {
    id: 'column',
    name: 'Column',
    nameCs: 'Sloupec',
    category: 'layout',
    step: null,
    icon: 'PanelLeft',
    locked: false,
    canReposition: true,
    canRestyle: true,
    description: 'Flexible column within a Row container.',
    descriptionCs: 'Flexibilni sloupec uvnitr kontejneru Radek.',
    defaultProps: {
      backgroundColor: 'transparent',
      borderColor: 'transparent',
      borderWidth: 0,
      borderStyle: 'none',
      borderRadius: 0,
      padding: { top: 0, right: 0, bottom: 0, left: 0 },
      margin: { top: 0, right: 0, bottom: 0, left: 0 },
      boxShadow: 'none',
      opacity: 1,
      flexBasis: 'auto',
      flexGrow: 1,
      flexShrink: 1,
      minWidth: 0,
      maxWidth: 'none',
      alignSelf: 'auto',
      gap: 8,
    },
    editableProperties: [
      {
        key: 'backgroundColor',
        label: 'Background',
        labelCs: 'Pozadi',
        type: 'color',
        default: 'transparent',
        group: 'container',
      },
      {
        key: 'borderColor',
        label: 'Border Color',
        labelCs: 'Barva ramecku',
        type: 'color',
        default: 'transparent',
        group: 'container',
      },
      {
        key: 'borderWidth',
        label: 'Border Width',
        labelCs: 'Sirka ramecku',
        type: 'number',
        default: 0,
        min: 0,
        max: 8,
        unit: 'px',
        group: 'container',
      },
      {
        key: 'borderRadius',
        label: 'Corner Radius',
        labelCs: 'Zaobleni rohu',
        type: 'number',
        default: 0,
        min: 0,
        max: 32,
        unit: 'px',
        group: 'container',
      },
      {
        key: 'padding',
        label: 'Padding',
        labelCs: 'Vnitrni odsazeni',
        type: 'spacing',
        default: { top: 0, right: 0, bottom: 0, left: 0 },
        group: 'container',
      },
      {
        key: 'margin',
        label: 'Margin',
        labelCs: 'Vnejsi odsazeni',
        type: 'spacing',
        default: { top: 0, right: 0, bottom: 0, left: 0 },
        group: 'container',
      },
      {
        key: 'boxShadow',
        label: 'Shadow',
        labelCs: 'Stin',
        type: 'shadow',
        default: 'none',
        options: [
          { value: 'none', label: 'None', labelCs: 'Zadny' },
          { value: '0 1px 3px rgba(0,0,0,0.1)', label: 'Small', labelCs: 'Maly' },
          { value: '0 4px 12px rgba(0,0,0,0.1)', label: 'Medium', labelCs: 'Stredni' },
        ],
        group: 'container',
      },
      {
        key: 'opacity',
        label: 'Opacity',
        labelCs: 'Pruhlednost',
        type: 'number',
        default: 1,
        min: 0,
        max: 1,
        step: 0.05,
        group: 'container',
      },
      {
        key: 'flexBasis',
        label: 'Flex Basis',
        labelCs: 'Zakladni sirka',
        type: 'select',
        default: 'auto',
        options: [
          { value: 'auto', label: 'Auto', labelCs: 'Automaticka' },
          { value: '25%', label: '25%', labelCs: '25%' },
          { value: '33.333%', label: '1/3', labelCs: '1/3' },
          { value: '50%', label: '50%', labelCs: '50%' },
          { value: '66.666%', label: '2/3', labelCs: '2/3' },
          { value: '75%', label: '75%', labelCs: '75%' },
          { value: '100%', label: '100%', labelCs: '100%' },
        ],
        group: 'layout',
      },
      {
        key: 'flexGrow',
        label: 'Grow',
        labelCs: 'Rust',
        type: 'number',
        default: 1,
        min: 0,
        max: 5,
        step: 1,
        group: 'layout',
      },
      {
        key: 'flexShrink',
        label: 'Shrink',
        labelCs: 'Smrsteni',
        type: 'number',
        default: 1,
        min: 0,
        max: 5,
        step: 1,
        group: 'layout',
      },
      {
        key: 'alignSelf',
        label: 'Align Self',
        labelCs: 'Vlastni zarovnani',
        type: 'select',
        default: 'auto',
        options: [
          { value: 'auto', label: 'Auto', labelCs: 'Automaticke' },
          { value: 'flex-start', label: 'Start', labelCs: 'Zacatek' },
          { value: 'center', label: 'Center', labelCs: 'Stred' },
          { value: 'flex-end', label: 'End', labelCs: 'Konec' },
          { value: 'stretch', label: 'Stretch', labelCs: 'Roztahnout' },
        ],
        group: 'layout',
      },
      {
        key: 'gap',
        label: 'Inner Gap',
        labelCs: 'Vnitrni mezera',
        type: 'number',
        default: 8,
        min: 0,
        max: 48,
        unit: 'px',
        group: 'layout',
      },
    ],
  },

  // -------------------------------------------------------------------------
  // Spacer
  // -------------------------------------------------------------------------
  {
    id: 'spacer',
    name: 'Spacer',
    nameCs: 'Mezera',
    category: 'layout',
    step: null,
    icon: 'MoveVertical',
    locked: false,
    canReposition: true,
    canRestyle: true,
    description: 'Vertical space with adjustable height.',
    descriptionCs: 'Vertikalni mezera s nastavitelnou vyskou.',
    defaultProps: {
      height: 24,
      backgroundColor: 'transparent',
    },
    editableProperties: [
      {
        key: 'height',
        label: 'Height',
        labelCs: 'Vyska',
        type: 'number',
        default: 24,
        min: 4,
        max: 200,
        unit: 'px',
        group: 'dimensions',
      },
      {
        key: 'backgroundColor',
        label: 'Background',
        labelCs: 'Pozadi',
        type: 'color',
        default: 'transparent',
        group: 'container',
      },
    ],
  },

  // -------------------------------------------------------------------------
  // Divider
  // -------------------------------------------------------------------------
  {
    id: 'divider',
    name: 'Divider',
    nameCs: 'Oddelovac',
    category: 'layout',
    step: null,
    icon: 'Minus',
    locked: false,
    canReposition: true,
    canRestyle: true,
    description: 'Horizontal divider line.',
    descriptionCs: 'Horizontalni oddelovaci linka.',
    defaultProps: {
      color: '#e5e7eb',
      thickness: 1,
      style: 'solid',
      margin: { top: 16, right: 0, bottom: 16, left: 0 },
      width: '100%',
      opacity: 1,
    },
    editableProperties: [
      {
        key: 'color',
        label: 'Color',
        labelCs: 'Barva',
        type: 'color',
        default: '#e5e7eb',
        group: 'container',
      },
      {
        key: 'thickness',
        label: 'Thickness',
        labelCs: 'Tloustka',
        type: 'number',
        default: 1,
        min: 1,
        max: 8,
        unit: 'px',
        group: 'container',
      },
      {
        key: 'style',
        label: 'Style',
        labelCs: 'Styl',
        type: 'select',
        default: 'solid',
        options: [
          { value: 'solid', label: 'Solid', labelCs: 'Plny' },
          { value: 'dashed', label: 'Dashed', labelCs: 'Carkovany' },
          { value: 'dotted', label: 'Dotted', labelCs: 'Teckovany' },
        ],
        group: 'container',
      },
      {
        key: 'margin',
        label: 'Margin',
        labelCs: 'Vnejsi odsazeni',
        type: 'spacing',
        default: { top: 16, right: 0, bottom: 16, left: 0 },
        group: 'container',
      },
      {
        key: 'width',
        label: 'Width',
        labelCs: 'Sirka',
        type: 'select',
        default: '100%',
        options: [
          { value: '100%', label: '100%', labelCs: '100%' },
          { value: '80%', label: '80%', labelCs: '80%' },
          { value: '60%', label: '60%', labelCs: '60%' },
          { value: '40%', label: '40%', labelCs: '40%' },
        ],
        group: 'dimensions',
      },
      {
        key: 'opacity',
        label: 'Opacity',
        labelCs: 'Pruhlednost',
        type: 'number',
        default: 1,
        min: 0,
        max: 1,
        step: 0.05,
        group: 'container',
      },
    ],
  },

  // -------------------------------------------------------------------------
  // Card
  // -------------------------------------------------------------------------
  {
    id: 'card',
    name: 'Card',
    nameCs: 'Karta',
    category: 'layout',
    step: null,
    icon: 'Square',
    locked: false,
    canReposition: true,
    canRestyle: true,
    description: 'Card container with shadow and border.',
    descriptionCs: 'Kontejner typu karta se stinem a rameckem.',
    defaultProps: {
      backgroundColor: '#ffffff',
      borderColor: '#e5e7eb',
      borderWidth: 1,
      borderStyle: 'solid',
      borderRadius: 12,
      padding: { top: 20, right: 20, bottom: 20, left: 20 },
      margin: { top: 0, right: 0, bottom: 16, left: 0 },
      boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
      opacity: 1,
      minHeight: 0,
      overflow: 'hidden',
      hoverShadow: '0 4px 12px rgba(0,0,0,0.1)',
      hoverBorderColor: '#d1d5db',
      transitionDuration: 150,
    },
    editableProperties: [
      {
        key: 'backgroundColor',
        label: 'Background',
        labelCs: 'Pozadi',
        type: 'color',
        default: '#ffffff',
        group: 'container',
      },
      {
        key: 'borderColor',
        label: 'Border Color',
        labelCs: 'Barva ramecku',
        type: 'color',
        default: '#e5e7eb',
        group: 'container',
      },
      {
        key: 'borderWidth',
        label: 'Border Width',
        labelCs: 'Sirka ramecku',
        type: 'number',
        default: 1,
        min: 0,
        max: 8,
        unit: 'px',
        group: 'container',
      },
      {
        key: 'borderStyle',
        label: 'Border Style',
        labelCs: 'Styl ramecku',
        type: 'select',
        default: 'solid',
        options: [
          { value: 'none', label: 'None', labelCs: 'Zadny' },
          { value: 'solid', label: 'Solid', labelCs: 'Plny' },
          { value: 'dashed', label: 'Dashed', labelCs: 'Carkovany' },
        ],
        group: 'container',
      },
      {
        key: 'borderRadius',
        label: 'Corner Radius',
        labelCs: 'Zaobleni rohu',
        type: 'number',
        default: 12,
        min: 0,
        max: 32,
        unit: 'px',
        group: 'container',
      },
      {
        key: 'padding',
        label: 'Padding',
        labelCs: 'Vnitrni odsazeni',
        type: 'spacing',
        default: { top: 20, right: 20, bottom: 20, left: 20 },
        group: 'container',
      },
      {
        key: 'margin',
        label: 'Margin',
        labelCs: 'Vnejsi odsazeni',
        type: 'spacing',
        default: { top: 0, right: 0, bottom: 16, left: 0 },
        group: 'container',
      },
      {
        key: 'boxShadow',
        label: 'Shadow',
        labelCs: 'Stin',
        type: 'shadow',
        default: '0 1px 3px rgba(0,0,0,0.1)',
        options: [
          { value: 'none', label: 'None', labelCs: 'Zadny' },
          { value: '0 1px 3px rgba(0,0,0,0.1)', label: 'Small', labelCs: 'Maly' },
          { value: '0 4px 12px rgba(0,0,0,0.1)', label: 'Medium', labelCs: 'Stredni' },
          { value: '0 8px 24px rgba(0,0,0,0.12)', label: 'Large', labelCs: 'Velky' },
          { value: '0 12px 40px rgba(0,0,0,0.15)', label: 'XL', labelCs: 'Extra velky' },
        ],
        group: 'container',
      },
      {
        key: 'opacity',
        label: 'Opacity',
        labelCs: 'Pruhlednost',
        type: 'number',
        default: 1,
        min: 0,
        max: 1,
        step: 0.05,
        group: 'container',
      },
      {
        key: 'minHeight',
        label: 'Min Height',
        labelCs: 'Minimalni vyska',
        type: 'number',
        default: 0,
        min: 0,
        max: 600,
        unit: 'px',
        group: 'dimensions',
      },
      {
        key: 'overflow',
        label: 'Overflow',
        labelCs: 'Preteceni',
        type: 'select',
        default: 'hidden',
        options: [
          { value: 'visible', label: 'Visible', labelCs: 'Viditelne' },
          { value: 'hidden', label: 'Hidden', labelCs: 'Skryte' },
          { value: 'auto', label: 'Auto', labelCs: 'Automaticke' },
        ],
        group: 'dimensions',
      },
      {
        key: 'hoverShadow',
        label: 'Hover Shadow',
        labelCs: 'Stin pri navrhu',
        type: 'shadow',
        default: '0 4px 12px rgba(0,0,0,0.1)',
        options: [
          { value: 'none', label: 'None', labelCs: 'Zadny' },
          { value: '0 1px 3px rgba(0,0,0,0.1)', label: 'Small', labelCs: 'Maly' },
          { value: '0 4px 12px rgba(0,0,0,0.1)', label: 'Medium', labelCs: 'Stredni' },
          { value: '0 8px 24px rgba(0,0,0,0.12)', label: 'Large', labelCs: 'Velky' },
        ],
        group: 'interaction',
      },
      {
        key: 'hoverBorderColor',
        label: 'Hover Border',
        labelCs: 'Ramecek pri navrhu',
        type: 'color',
        default: '#d1d5db',
        group: 'interaction',
      },
      {
        key: 'transitionDuration',
        label: 'Transition (ms)',
        labelCs: 'Doba prechodu (ms)',
        type: 'number',
        default: 150,
        min: 0,
        max: 500,
        step: 50,
        unit: 'ms',
        group: 'interaction',
      },
    ],
  },
];
